[SPARK-40044][SQL] Fix the target interval type in cast overflow errors
### What changes were proposed in this pull request?
In the PR, I propose to fix the incorrect target type in the error message of the cast overflow. For example:
```sql
spark-sql> select CAST(9223372036854775807L AS INTERVAL YEAR TO MONTH);
org.apache.spark.SparkArithmeticException: [CAST_OVERFLOW] The value 9223372036854775807L of the type "BIGINT" cannot be cast to "INTERVAL MONTH" due to an overflow.
```
The target type is **"INTERVAL MONTH"** instead of **"INTERVAL YEAR TO MONTH"**.

### Why are the changes needed?
To improve user experience with Spark SQL, and do not confuse users by incorrect error messages.

### Does this PR introduce _any_ user-facing change?
Yes, it changes user-facing error messages.

After the changes, for the example above:
```sql
spark-sql> select CAST(9223372036854775807L AS INTERVAL YEAR TO MONTH);
org.apache.spark.SparkArithmeticException: [CAST_OVERFLOW] The value 9223372036854775807L of the type "BIGINT" cannot be cast to "INTERVAL YEAR TO MONTH" due to an overflow.
```

### How was this patch tested?
By running new test:
```
$  build/sbt "test:testOnly *QueryExecutionErrorsSuite"
```

Closes #37470 from MaxGekk/fix-cast-target-decimal-on-overflow.

Authored-by: Max Gekk <max.gekk@gmail.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>