[SPARK-48757][CORE] Make `IndexShuffleBlockResolver` have explicit constructors
### What changes were proposed in this pull request?

This PR aims to make `IndexShuffleBlockResolver` have explicit constructors from Apache Spark 4.0.0.

### Why are the changes needed?

Although `IndexShuffleBlockResolver` is `private` and there is no contract to keep class constructor signatures, from Apache Spark 4.0.0, we had better reduce the following situations with the old libraries built against old Spark versions.

```
Cause: java.lang.NoSuchMethodError: 'void org.apache.spark.shuffle.IndexShuffleBlockResolver.<init>(org.apache.spark.SparkConf, org.apache.spark.storage.BlockManager)'
[info] at org.apache.spark.sql.comet.execution.shuffle.CometShuffleManager.<init>(CometShuffleManager.scala:64)
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #47148 from dongjoon-hyun/SPARK-48757.

Authored-by: Dongjoon Hyun <dhyun@apple.com>
Signed-off-by: Dongjoon Hyun <dhyun@apple.com>