[SPARK-42275][CONNECT][PYTHON] Avoid using built-in list, dict in static typing
### What changes were proposed in this pull request?
Avoid using built-in list, dict in static typing

### Why are the changes needed?
it's not supported in python 3.8, see https://peps.python.org/pep-0585/

python 3.8
```
>>> from typing import List
>>> a : List[str] = ["a", "b"]
>>> a : list[str] = ["a", "b"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'type' object is not subscriptable
```

python 3.9
```
>>> from typing import List
>>> a : List[str] = ["a", "b"]
>>> a : list[str] = ["a", "b"]

```

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
manually check

Closes #39844 from zhengruifeng/connect_fix_list.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>