[SPARK-43032][SS][CONNECT] Python SQM bug fix
### What changes were proposed in this pull request?

Some bug fix for streaming ***connect*** python SQM

Note that I also changed ***non-connect***'s StreamingQueryManager `get()` API to return an `Optional[StreamingQuery]`.

Before it looks like this when you get a non-exist query:

```
>>> a = spark.streams.get("00000000-0000-0001-0000-000000000001")
>>> a
<pyspark.sql.streaming.query.StreamingQuery object at 0x7f86465702b0>
>>> a.id
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wei.liu/oss-spark/python/pyspark/sql/streaming/query.py", line 78, in id
    return self._jsq.id().toString()
AttributeError: 'NoneType' object has no attribute 'id'
```

But now it looks like:
```
>>> a = spark.streams.get("00000000-0000-0001-0000-000000000001")
>>> a.id
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'id'
```
The only difference is the return type, which is not typically honored in Python... But not very sure if that's a breaking change

### Why are the changes needed?

Bug fix

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Manually tested. Also verified that it won't throw even without this fix so it's not that urgent

Closes #41037 from WweiL/SPARK-43032-python-sqm-fix.

Authored-by: Wei Liu <wei.liu@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>