[SPARK-49443][SQL][FOLLOWUP] Fix formatting of a comment for `to_variant_object()`
### What changes were proposed in this pull request?
Fix formatting of comments for the function `to_variant_object()`.

### Why are the changes needed?
To fix the failure:
```
Error:  Failed to execute goal org.antipathy:mvn-scalafmt_2.13:1.1.1713302731.c3d0074:format (default-cli) on project spark-sql-api_2.13: Error formatting Scala files: Scalafmt: Unformatted files found -> [Help 1]
```

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
By running the formatting:
```
$ ./build/mvn scalafmt:format -Dscalafmt.skip=false -Dscalafmt.validateOnly=false -Dscalafmt.changedOnly=false -pl sql/api -pl sql/connect/common -pl sql/connect/server -pl connector/connect/client/jvm
```

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #48060 from MaxGekk/fix-formating.

Authored-by: Max Gekk <max.gekk@gmail.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>