[SPARK-48717][PYTHON][SS] Catch ForeachBatch py4j InterruptedException better in classic PySpark
### What changes were proposed in this pull request?

In https://issues.apache.org/jira/browse/SPARK-39218, there is a fix when python pinned thread mode is on, and `query.stop()` sends an interrupted signal, for example (from the original ticket):

```
import time

def func(batch_df, batch_id):
    time.sleep(10)
    print(batch_df.count())

q = spark.readStream.format("rate").load().writeStream.foreachBatch(func).start()
time.sleep(5)
q.stop()
```

Because all python errors are wrapped inside `PY4JJavaError`, the fix was to do reg-ex match on that error string:
https://github.com/apache/spark/blob/3e39033c36f0aa534c738973b06a1c741ac951f9/sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/StreamExecution.scala#L690-L692

However, this regex only checks the case when the exception is thrown in `time.sleep(10)` (my understanding). So only errors like this would be captured:
```
py4j.protocol.Py4JJavaError: An error occurred while calling o44.count.
: java.lang.InterruptedException
```

But say the interrupted signal is sent when executing a spark query:

```
def func(batch_df, batch_id):
    batch_df.sparkSession.range(10000000).write.saveAsTable("oops")
    print(batch_df.count())
```

Then we would see such errors:
```
py4j.protocol.Py4JJavaError: An error occurred while calling o2141502.saveAsTable.
: org.apache.spark.SparkException: Job aborted.
<REDACTED>
<REDACTED>
<REDACTED>
...
at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.$anonfun$run$2(StreamExecution.scala:262)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:262)
*Caused by: java.lang.InterruptedException
at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1000)*
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1308)
```

In such cases, query.stop() would actually cause the query to throw, although it shouldn't.

In this PR, we propose to relax the regex and match more InterruptedException.

### Why are the changes needed?

Bug fix

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Added unit test

### Was this patch authored or co-authored using generative AI tooling?

No

Closes #47093 from WweiL/SPARK-48717-feb-python-error-unwrap.

Authored-by: Wei Liu <wei.liu@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>