[SPARK-43077][SQL] Improve the error message of UNRECOGNIZED_SQL_TYPE
### What changes were proposed in this pull request?

This PR makes UNRECOGNIZED_SQL_TYPE print both the column type name and the id.

### Why are the changes needed?

UNRECOGNIZED_SQL_TYPE prints the jdbc type id in the error message currently. This is difficult for spark users to understand the meaning of this kind of error, especially when the type id is from a vendor extension.

For example,

```java
 org.apache.spark.SparkSQLException: Unrecognized SQL type -102
```

While -102 is nonstandard, it's hard to know what type it is

```
classOf[java.sql.JDBCType].getEnumConstants.foreach(t => println(t.getName + "|" + t.getVendorTypeNumber))
BIT|-7
TINYINT|-6
SMALLINT|5
INTEGER|4
BIGINT|-5
FLOAT|6
REAL|7
DOUBLE|8
NUMERIC|2
DECIMAL|3
CHAR|1
VARCHAR|12
LONGVARCHAR|-1
DATE|91
TIME|92
TIMESTAMP|93
BINARY|-2
VARBINARY|-3
LONGVARBINARY|-4
NULL|0
OTHER|1111
JAVA_OBJECT|2000
DISTINCT|2001
STRUCT|2002
ARRAY|2003
BLOB|2004
CLOB|2005
REF|2006
DATALINK|70
BOOLEAN|16
ROWID|-8
NCHAR|-15
NVARCHAR|-9
LONGNVARCHAR|-16
NCLOB|2011
SQLXML|2009
REF_CURSOR|2012
TIME_WITH_TIMEZONE|2013
TIMESTAMP_WITH_TIMEZONE|2014
```

### Does this PR introduce _any_ user-facing change?

yes, the unrecognized jdbc type error will also print the type name

For example,

```java
 org.apache.spark.SparkSQLException: Unrecognized SQL type - name: TIMESTAMP WITH LOCAL TIME ZONE, id: -102
```

### How was this patch tested?

new tests

Closes #40718 from yaooqinn/SPARK-43077.

Authored-by: Kent Yao <yao@apache.org>
Signed-off-by: Kent Yao <yao@apache.org>