[SPARK-51087][PYTHON][CONNECT] Raise a warning when memory-profiler is not installed for memory profiling
### What changes were proposed in this pull request?
Raise a warning when memory-profiler is not installed for memory profiling.

### Why are the changes needed?
Better usability of PySpark UDF memory profiling.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Existing and manual tests as shown below:
```py
>>> import memory_profiler  # when memory-profiler is not installed
Traceback (most recent call last):
...
ModuleNotFoundError: No module named 'memory_profiler'

>>> from pyspark.sql.functions import pandas_udf
>>>
>>> df = spark.range(10)
>>> pandas_udf("long")
... def add1(x):
...   return x + 1
...
>>> added = df.select(add1("id"))
>>>
>>> spark.conf.set("spark.sql.pyspark.udf.profiler", "memory")
>>> added.show()
+--------+
|add1(id)|
+--------+
|       1|
|       2|
|       3|
|       4|
|       5|
|       6|
|       7|
|       8|
|       9|
|      10|
+--------+
>>> spark.profile.show(type="memory")
/Users/xinrong.meng/spark/python/pyspark/sql/profiler.py:141: UserWarning: Install the 'memory_profiler' library in the cluster to enable memory profiling
...
>>> spark.profile.dump(path='...', type="memory")
/Users/xinrong.meng/spark/python/pyspark/sql/profiler.py:225: UserWarning: Install the 'memory_profiler' library in the cluster to enable memory profiling
...
```

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #49797 from xinrong-meng/memory_profiler_install.

Authored-by: Xinrong Meng <xinrong@apache.org>
Signed-off-by: Xinrong Meng <xinrong@apache.org>