[SPARK-40601][PYTHON] Assert identical key size when cogrouping groups
Cogrouping two grouped DataFrames in PySpark that have different group key cardinalities raises an error that is not very descriptive:

```python
left.groupby("id", "k")
    .cogroup(right.groupby("id"))
```

```
py4j.protocol.Py4JJavaError: An error occurred while calling o726.collectToPython.
: java.lang.IndexOutOfBoundsException: 1
	at scala.collection.mutable.ResizableArray.apply(ResizableArray.scala:46)
	at scala.collection.mutable.ResizableArray.apply$(ResizableArray.scala:45)
	at scala.collection.mutable.ArrayBuffer.apply(ArrayBuffer.scala:49)
	at org.apache.spark.sql.catalyst.plans.physical.HashShuffleSpec.$anonfun$createPartitioning$5(partitioning.scala:650)
...
org.apache.spark.sql.execution.exchange.EnsureRequirements.$anonfun$ensureDistributionAndOrdering$14(EnsureRequirements.scala:159)
```

### What changes were proposed in this pull request?
Assert identical size of groupby keys and provide a meaningful error on cogroup.

### Why are the changes needed?
The error does not provide information on how to solve the problem.

### Does this PR introduce _any_ user-facing change?
Yes, raises an `AssertionError: group keys must have same size` instead.

### How was this patch tested?
Adds test `test_different_group_key_cardinality` to `pyspark.sql.tests.test_pandas_cogrouped_map`.

Closes #38036 from EnricoMi/branch-cogroup-key-mismatch.

Authored-by: Enrico Minack <github@enrico.minack.dev>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>