[SPARK-46074][CONNECT][SCALA] Insufficient details in error message on UDF failure
### What changes were proposed in this pull request?

Update the error message for 'FAILED_EXECUTE_UDF' with the underlying error
message.

### Why are the changes needed?

The Spark Connect client does not receive the underlying cause for a UDF failure.
This means that a user needs to go into the driver logs to identify the cause for
failure.

Update the error message so that the underlying exception's message is included.

### Does this PR introduce _any_ user-facing change?

Yes. This changes the error message that the user sees when a UDF fails. A new error
parameter is added but the SQL state and existing parameters are unchanged and should
cause no regressions.

The error message prior to this change:

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 3 in stage 0.0 failed 1 times, most recent failure: Lost task 3.0 in stage 0.0 (TID 3) (192.168.188.21 executor driver): org.apache.spark.SparkException: [FAILED_EXECUTE_UDF] Failed to execute user defined function (` (cmd2$Helper$$Lambda$2170/0x000000f001d23000)`: (int) => int). SQLSTATE: 39000
```

Sample of the new error message:

```
org.apache.spark.SparkException: [FAILED_EXECUTE_UDF] User defined function (` (cmd2$Helper$$Lambda$2422/0x0000007001ec1a10)`: (int) => int) failed due to: java.lang.NoClassDefFoundError: com/nija/test/MyClass. SQLSTATE: 39000
```

### How was this patch tested?

Tested manually by running a [local connect server] and [connect client REPL]

[local connect server]: https://github.com/apache/spark/blob/master/connector/connect/bin/spark-connect-shell
[connect client REPL]: https://github.com/apache/spark/blob/master/connector/connect/bin/spark-connect-scala-client

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #43983 from nija-at/udf-error-msg.

Authored-by: Niranjan Jayakar <nija@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>