[SPARK-51677][CONNECT][TESTS] Refactor `ClientE2ETestSuite/SparkSessionE2ESuite` to prevent memory leaks related to Arrow
### What changes were proposed in this pull request?
This pr refactors the `ClientE2ETestSuite` and `SparkSessionE2ESuite` as follows to prevent memory leaks related to Arrow:

1. Replace `df.collectResult` with `df.withResult` to ensure that `SparkResult` is automatically closed after use.

https://github.com/apache/spark/blob/58b4ca264d8d78282f56c6e465f07917c0979bc7/sql/connect/common/src/main/scala/org/apache/spark/sql/connect/Dataset.scala#L1230-L1236

2. Use a `try {} finally {}` block to ensure that `SparkResult#destructiveIterator` and `SparkResult#iterator` are closed after use.

### Why are the changes needed?
Prevent memory leaks related to Arrow in `ClientE2ETestSuite` and `SparkSessionE2ESuite`.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
- Pass GitHub Actions
- Locally check:

```
build/sbt clean "connect-client-jvm/test" -Phive -Dspark.debug.sc.jvm.client=true
```

**Before**

```
...
[info] ClientE2ETestSuite:
...
[info] - SPARK-50965: Multiple named and positional parameterized nodes in the parsed logical plan (39 milliseconds)
java.lang.IllegalStateException: Memory was leaked by query. Memory leaked: (12192)
Allocator(ROOT) 0/12192/6325056/9223372036854775807 (res/actual/peak/limit)

	at org.apache.arrow.memory.BaseAllocator.close(BaseAllocator.java:504)
	at org.apache.arrow.memory.RootAllocator.close(RootAllocator.java:27)
	at org.apache.spark.sql.connect.SparkSession.close(SparkSession.scala:632)
	at org.apache.spark.sql.SparkSession.stop(SparkSession.scala:783)
	at org.apache.spark.sql.connect.test.RemoteSparkSession.afterAll(RemoteSparkSession.scala:226)
	at org.apache.spark.sql.connect.test.RemoteSparkSession.afterAll$(RemoteSparkSession.scala:224)
	at org.apache.spark.sql.connect.ClientE2ETestSuite.afterAll(ClientE2ETestSuite.scala:51)
	at org.scalatest.BeforeAndAfterAll.$anonfun$run$1(BeforeAndAfterAll.scala:225)
	at org.scalatest.Status.$anonfun$withAfterEffect$1(Status.scala:377)
	at org.scalatest.Status.$anonfun$withAfterEffect$1$adapted(Status.scala:373)
	at org.scalatest.CompositeStatus.whenCompleted(Status.scala:962)
	at org.scalatest.Status.withAfterEffect(Status.scala:373)
	at org.scalatest.Status.withAfterEffect$(Status.scala:371)
	at org.scalatest.CompositeStatus.withAfterEffect(Status.scala:863)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:224)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at org.apache.spark.sql.connect.ClientE2ETestSuite.run(ClientE2ETestSuite.scala:51)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:517)
	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:414)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
...
[info] SparkSessionE2ESuite:
...
[info] - executeCommand (19 milliseconds)
java.lang.IllegalStateException: Memory was leaked by query. Memory leaked: (128000)
Allocator(ROOT) 0/128000/128032/9223372036854775807 (res/actual/peak/limit)

	at org.apache.arrow.memory.BaseAllocator.close(BaseAllocator.java:504)
	at org.apache.arrow.memory.RootAllocator.close(RootAllocator.java:27)
	at org.apache.spark.sql.connect.SparkSession.close(SparkSession.scala:632)
	at org.apache.spark.sql.SparkSession.stop(SparkSession.scala:783)
	at org.apache.spark.sql.connect.test.RemoteSparkSession.afterAll(RemoteSparkSession.scala:226)
	at org.apache.spark.sql.connect.test.RemoteSparkSession.afterAll$(RemoteSparkSession.scala:224)
	at org.apache.spark.sql.connect.SparkSessionE2ESuite.afterAll(SparkSessionE2ESuite.scala:38)
	at org.scalatest.BeforeAndAfterAll.$anonfun$run$1(BeforeAndAfterAll.scala:225)
	at org.scalatest.Status.$anonfun$withAfterEffect$1(Status.scala:377)
	at org.scalatest.Status.$anonfun$withAfterEffect$1$adapted(Status.scala:373)
	at org.scalatest.CompositeStatus.whenCompleted(Status.scala:962)
	at org.scalatest.Status.withAfterEffect(Status.scala:373)
	at org.scalatest.Status.withAfterEffect$(Status.scala:371)
	at org.scalatest.CompositeStatus.withAfterEffect(Status.scala:863)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:224)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at org.apache.spark.sql.connect.SparkSessionE2ESuite.run(SparkSessionE2ESuite.scala:38)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:517)
	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:414)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

**After**

The aforementioned logs no longer exist.

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #50493 from LuciferYang/connect-memleak.

Authored-by: yangjie01 <yangjie01@baidu.com>
Signed-off-by: yangjie01 <yangjie01@baidu.com>
(cherry picked from commit 4e4b2f5cabe99eda73b1e51755ee7bc8627aaf03)
Signed-off-by: yangjie01 <yangjie01@baidu.com>