[SPARK-41157][CONNECT][PYTHON][TEST] Show detailed differences in dataframe comparison
### What changes were proposed in this pull request?
use `assert_eq` in `PandasOnSparkTestCase` to compare dataframes

### Why are the changes needed?
show detailed error message

before:
```
======================================================================
ERROR [0.667s]: test_fill_na (pyspark.sql.tests.connect.test_connect_basic.SparkConnectTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/python/pyspark/sql/tests/connect/test_connect_basic.py", line 244, in test_fill_na
    self.assertTrue(
AssertionError: False is not true
----------------------------------------------------------------------
```

after:
```
AssertionError: DataFrame.iloc[:, 0] (column name="id") are different

DataFrame.iloc[:, 0] (column name="id") values are different (100.0 %)
[index]: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[left]:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[right]: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Left:
   id
id    int64
dtype: object

Right:
   id
id    int64
dtype: object
```

### Does this PR introduce _any_ user-facing change?
No, test only

### How was this patch tested?
existing UT

Closes #38670 from zhengruifeng/connect_test_df_equal.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>