[SPARK-41441][SQL] Support Generate with no required child output to host outer references
### What changes were proposed in this pull request?
This PR supports `Generate` with no required child output to host outer references. It updates DecorrelateInnerQuery to handle Generate and adds a new optimization for Generate and OneRowRelation in rule OptimizeOneRowRelationSubquery.

### Why are the changes needed?
Currently, CheckAnalysis allows `Generate` with no required child output to host outer references. However,  DecorrelateInnerQuery does not handle this case correctly.  For example
```
select * from t, lateral (select explode(array(c1, c2)))
```
This will throw an internal error:
```
AssertionError: assertion failed: Correlated column is not allowed in Generate
```

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Unit tests and SQL query tests.

Closes #38968 from allisonwang-db/spark-41441-outer-in-generate.

Authored-by: allisonwang-db <allison.wang@databricks.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>