[SPARK-51496][SQL] CaseInsensitiveStringMap comparison should ignore case
### What changes were proposed in this pull request?
Since both `commandOptions` and `dsOptions` are `CaseInsensitiveStringMap` objects, I think we should convert the keys and values to lowercase before comparing them

### Why are the changes needed?

In iceberg/spark4.0 integration, I got a few assertion errors:
```
assertion failed
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:264)
	at org.apache.spark.sql.execution.datasources.v2.V2Writes$.org$apache$spark$sql$execution$datasources$v2$V2Writes$$mergeOptions(V2Writes.scala:128)
```

The assertion error occurs when comparing commandOptions and dsOptions; the cases of the keys don't match.
```
assert(commandOptions == dsOptions)
```

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
I have verified that the iceberg tests can pass with this fix.

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #50275 from huaxingao/mergeOptions.

Authored-by: huaxingao <huaxin.gao11@gmail.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>
(cherry picked from commit a43d53afcbc4cba89145b8e0818ad2d8cde9c9fe)
Signed-off-by: Wenchen Fan <wenchen@databricks.com>