[SPARK-42895][CONNECT] Improve error messages for stopped Spark sessions
### What changes were proposed in this pull request?

This PR improves error messages when users attempt to invoke session operations on a stopped Spark session.

### Why are the changes needed?
To make the error messages more user-friendly.

For example:
```python
spark.stop()
spark.sql("select 1")
```
Before this PR, this code will throw two exceptions:
```
ValueError: Cannot invoke RPC: Channel closed!

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  ...
    return e.code() == grpc.StatusCode.UNAVAILABLE
AttributeError: 'ValueError' object has no attribute 'code'
```

After this PR, it will show this exception:
```
[NO_ACTIVE_SESSION] No active Spark session found. Please create a new Spark session before running the code.
```

### Does this PR introduce _any_ user-facing change?
Yes. This PR modifies the error messages.

### How was this patch tested?

New unit test.

Closes #40536 from allisonwang-db/spark-42895-stopped-session.

Authored-by: allisonwang-db <allison.wang@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>