[SPARK-39262][PYTHON] Correct the behavior of creating DataFrame from an RDD
### What changes were proposed in this pull request?
Correct the behavior of creating DataFrame from an RDD **with `0` as the first element**.

See **Does this PR introduce _any_ user-facing change?** for the corrected behaviors.

### Why are the changes needed?
Improve error messages and debugability.

### Does this PR introduce _any_ user-facing change?

Before:
```py
>>> spark.createDataFrame(spark._sc.parallelize([0, 1]))
Traceback (most recent call last):
...
ValueError: The first row in RDD is empty, can not infer schema
```

After:
```py
>>> spark.createDataFrame(spark._sc.parallelize([0, 1]))
Traceback (most recent call last):
...
TypeError: Can not infer schema for type: <class 'int'>
```

### How was this patch tested?
Existing tests.

Closes #36640 from xinrong-databricks/session._inferSchema.

Authored-by: Xinrong Meng <xinrong.meng@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>