[MINOR][PS] Workaround to remove several ignores
### What changes were proposed in this pull request?

This PR workaround several `ignore`s in MyPy check

### Why are the changes needed?

To make MyPy happy.

In addition, It fails (in my local) although I use the exactly same MyPy version.

```
annotations failed mypy checks:
python/pyspark/pandas/frame.py:6371: error: unused "type: ignore" comment
python/pyspark/pandas/frame.py:6428: error: unused "type: ignore" comment
python/pyspark/pandas/frame.py:6430: error: unused "type: ignore" comment
python/pyspark/pandas/resample.py:104: error: unused "type: ignore" comment
python/pyspark/pandas/resample.py:137: error: unused "type: ignore" comment
Found 5 errors in 2 files (checked 375 source files)
```

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?

Manually tested via `./dev/lint-python` in my local.

Closes #39075 from HyukjinKwon/remove-unused-ignores.

Authored-by: Hyukjin Kwon <gurwls223@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>