[SPARK-51354][K8S][TEST][DOC] Fix sbt K8s integration test arg javaImageTag
### What changes were proposed in this pull request?

As title.

### Why are the changes needed?

When I follow the dev docs to run K8s IT using sbt, and set `spark.kubernetes.test.javaImageTag` to change the JDK image

```
$ build/sbt -Pkubernetes -Pkubernetes-integration-tests \
  -Dspark.kubernetes.test.javaImageTag=17 \
  -Dspark.kubernetes.test.namespace=default \
  -Dtest.exclude.tags=local,r,minikube \
  "kubernetes-integration-tests/test"
```

I face the following errors
```
Dockerfile:19
--------------------
  17 |     ARG java_image_tag=21
  18 |
  19 | >>> FROM azul/zulu-openjdk:${java_image_tag}
  20 |     LABEL org.opencontainers.image.authors="Apache Spark project <devspark.apache.org>"
  21 |     LABEL org.opencontainers.image.licenses="Apache-2.0"
--------------------
ERROR: failed to solve: failed to parse stage name "azul/zulu-openjdk:Some(17)": invalid reference format
Failed to build Spark JVM Docker image, please refer to Docker build output for details.
[error] java.lang.IllegalStateException: Process '/Users/chengpan/Projects/apache-spark/bin/docker-image-tool.sh -r docker.io/kubespark -t dev -p /Users/chengpan/Projects/apache-spark/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/bindings/python/Dockerfile -R  -b java_image_tag=Some(17) build' exited with 1.
[error] 	at KubernetesIntegrationTests$.$anonfun$settings$66(SparkBuild.scala:1020)
...
```

### Does this PR introduce _any_ user-facing change?

No, dev only.

### How was this patch tested?

```
$ build/sbt -Pkubernetes -Pkubernetes-integration-tests \
  -Dspark.kubernetes.test.javaImageTag=17 \
  -Dspark.kubernetes.test.namespace=default \
  -Dtest.exclude.tags=local,r,minikube \
  "kubernetes-integration-tests/test"
```
Correctly trigger the K8s integration tests.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #50113 from pan3793/SPARK-51354.

Authored-by: Cheng Pan <chengpan@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>