[SPARK-47147][PYTHON][SQL] Fix PySpark collated string conversion error
### What changes were proposed in this pull request?

When running Pyspark shell in non-Spark Connect mode, query `SELECT 'abc' COLLATE 'UCS_BASIC_LCASE'` produces the following error:
```
AssertionError: Undefined error message parameter for error class: CANNOT_PARSE_DATATYPE. Parameters: {'error': "Undefined error message parameter for error class: CANNOT_PARSE_DATATYPE. Parameters: {'error': 'string(UCS_BASIC_LCASE)'}"}
```
Fix the error by updating `StringType` class to include collation id support. Additional changes ensure conversions work properly.

### Why are the changes needed?

To fix collations-related error in PySpark shell.

### Does this PR introduce _any_ user-facing change?

Yes, the described sql query no longer throws an exception.

### How was this patch tested?

Manually tested with PySpark shell, additional assertions are added to type tests.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #45257 from nikolamand-db/nikolamand-db/SPARK-47147.

Authored-by: Nikola Mandic <nikola.mandic@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>