[SPARK-52482][SQL][CORE] Improve exception handling for reading certain corrupt zstd files
### What changes were proposed in this pull request?

This PR makes us handle skipping corrupted files more consistently by catching a different type of exception that may arise from reading corrupted files.

### Why are the changes needed?

Reading files compressed with ZSTD corrupted in some ways yields an exception type we catch and compressed files corrupted in other ways results in an exception we don't. This means that sometimes the `ignoreCorruptFiles` setting is sometimes not respected depending on how the file is corrupted.

For example:

Reading a file with the last 10 bytes removed:
```
scala> spark.read.option("ignoreCorruptFiles", "true").csv("scratch/corrupt_tail.csv.zst").count()
val res3: Long = 0
```

Reading a file with the first 10 bytes removed:
```
scala> spark.read.option("ignoreCorruptFiles", "true").csv("scratch/corrupt_head.csv.zst").count()
25/08/08 19:31:31 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.InternalError: Unknown frame descriptor
	at org.apache.hadoop.io.compress.zstd.ZStandardDecompressor.inflateBytesDirect(Native Method)
	at org.apache.hadoop.io.compress.zstd.ZStandardDecompressor.decompress(ZStandardDecompressor.java:187)
	at org.apache.hadoop.io.compress.DecompressorStream.decompress(DecompressorStream.java:111)
	...
```

This diff makes it so that errors that result from ZSTD codec, including the latter's InternalError, does not cause this inconsistency.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Added tests in CSVSuite

### Was this patch authored or co-authored using generative AI tooling?

No

Closes #51916 from mzhang/corrupted-zst.

Authored-by: Matt Zhang <matt@zhang.software>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>