[SPARK-48841][SQL] Include `collationName` to `sql()` of `Collate`
### What changes were proposed in this pull request?
In the PR, I propose to fix the `sql()` method of the `Collate` expression, and append the `collationName` clause.

### Why are the changes needed?
To distinguish column names when the `collationName` argument is used by `collate`. Before the changes, columns might conflict like the example below, and that could confuse users:
```
sql("CREATE TEMP VIEW tbl as (SELECT collate('A', 'UTF8_BINARY'), collate('A', 'UTF8_LCASE'))")
```
- Before:
```
[COLUMN_ALREADY_EXISTS] The column `collate(a)` already exists. Choose another name or rename the existing column. SQLSTATE: 42711
org.apache.spark.sql.AnalysisException: [COLUMN_ALREADY_EXISTS] The column `collate(a)` already exists. Choose another name or rename the existing column. SQLSTATE: 42711
	at org.apache.spark.sql.errors.QueryCompilationErrors$.columnAlreadyExistsError(QueryCompilationErrors.scala:2595)
	at org.apache.spark.sql.util.SchemaUtils$.checkColumnNameDuplication(SchemaUtils.scala:115)
	at org.apache.spark.sql.util.SchemaUtils$.checkColumnNameDuplication(SchemaUtils.scala:97)
```

- After:
```
describe extended tbl;
+-----------------------+-------------------------+-------+
|col_name               |data_type                |comment|
+-----------------------+-------------------------+-------+
|collate(A, UTF8_BINARY)|string                   |NULL   |
|collate(A, UTF8_LCASE) |string collate UTF8_LCASE|NULL   |
+-----------------------+-------------------------+-------+

```

### Does this PR introduce _any_ user-facing change?
Should not.

### How was this patch tested?
Update existed UT.

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #47265 from panbingkun/SPARK-48841.

Authored-by: panbingkun <panbingkun@baidu.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>