[SPARK-37407][FOLLOW-UP][PYTHON][ML] Add not None assertions for active context and its _jvm
### What changes were proposed in this pull request?

This PR add  `is not None` assertions for `Optional`  `_active_spark_context` and `_jvm`

### Why are the changes needed?

To address failures in CI:

```
python/pyspark/ml/functions.py:69: error: Item "None" of "Optional[SparkContext]" has no attribute "_jvm"  [union-attr]
python/pyspark/ml/functions.py:69: error: Item "None" of "Optional[Any]" has no attribute "org"  [union-attr]
python/pyspark/ml/functions.py:104: error: Item "None" of "Optional[SparkContext]" has no attribute "_jvm"  [union-attr]
python/pyspark/ml/functions.py:104: error: Item "None" of "Optional[Any]" has no attribute "org"  [union-attr]
```

caused by divergence between #34678 and changes introduced by #34892

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

`dev/lint-python`

Closes #35022 from zero323/SPARK-37407-FOLLOW-UP.

Authored-by: zero323 <mszymkiewicz@gmail.com>
Signed-off-by: zero323 <mszymkiewicz@gmail.com>