[SPARK-43509][PYTHON][CONNECT][FOLLOW-UP] Set SPARK_CONNECT_MODE_ENABLED when running pyspark shell with remote is local
### What changes were proposed in this pull request?

This PR is a followup of https://github.com/apache/spark/pull/41013 that sets `SPARK_CONNECT_MODE_ENABLED` when running PySpark shell via `bin/pyspark --remote=local` so it works.

### Why are the changes needed?

It is broken after the PR:

```bash
./bin/pyspark --remote local
```

```python
...
Traceback (most recent call last):
  File "/.../python/pyspark/shell.py", line 78, in <module>
    sc = spark.sparkContext
  File "/.../python/pyspark/sql/connect/session.py", line 567, in sparkContext
    raise PySparkNotImplementedError(
pyspark.errors.exceptions.base.PySparkNotImplementedError: [NOT_IMPLEMENTED] sparkContext() is not implemented.
```

### Does this PR introduce _any_ user-facing change?

No to end users.

Yes to the dev as described above.

### How was this patch tested?

Manually tested via `./bin/pyspark --remote local`

Closes #41206 from HyukjinKwon/SPARK-43509-followup.

Authored-by: Hyukjin Kwon <gurwls223@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>