[SPARK-53305][PYTHON] Support TimeType in createDataFrame
### What changes were proposed in this pull request?
Support TimeType in createDataFrame

### Why are the changes needed?
```
In [1]: import datetime

In [2]: spark.createDataFrame([(datetime.time(12,10,1),)])
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 spark.createDataFrame([(datetime.time(12,10,1),)])

...

File ~/spark/python/pyspark/sql/types.py:441, in TimestampType.toInternal(self, dt)
    438 def toInternal(self, dt: datetime.datetime) -> int:
    439     if dt is not None:
    440         seconds = (
--> 441             calendar.timegm(dt.utctimetuple()) if dt.tzinfo else time.mktime(dt.timetuple())
    442         )
    443         return int(seconds) * 1000000 + dt.microsecond

AttributeError: 'datetime.time' object has no attribute 'timetuple'
```

### Does this PR introduce _any_ user-facing change?

### How was this patch tested?
new tests

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #52058 from zhengruifeng/create_df_time.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>