[SPARK-42063][CORE] Register `byte[][]` to KyroSerializer
### What changes were proposed in this pull request?

This PR aims to register `byte[][]` to `KryoSerializer`.

### Why are the changes needed?

Spark uses `byte[][]` internally and it causes failure when we use `spark.kryo.registrationRequired=true`.
```
java.lang.IllegalArgumentException: Class is not registered: byte[][]
Note: To register this class use: kryo.register(byte[][].class);
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs with the newly added test case.

Closes #39569 from dongjoon-hyun/SPARK-42063.

Authored-by: Dongjoon Hyun <dongjoon@apache.org>
Signed-off-by: Yuming Wang <yumwang@ebay.com>