[SPARK-50606][CONNECT] Fix NPE on uninitiated SessionHolder
### What changes were proposed in this pull request?

This PR fixes NPE like,

```scala
{"ts":"2024-12-18T05:41:52.977Z","level":"ERROR","msg":"Exception while executing runnable org.sparkproject.connect.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable418f1536","exception":{"class":"java.lang.NullPointerException","msg":"Cannot invoke \"org.apache.spark.sql.connect.service.SessionHolder.userId()\" because the return value of \"org.apache.spark.sql.connect.service.SparkConnectAddArtifactsHandler.holder()\" is null","stacktrace":[{"class":"org.apache.spark.sql.connect.service.SparkConnectAddArtifactsHandler","method":"onNext","file":"SparkConnectAddArtifactsHandler.scala","line":90},{"class":"org.apache.spark.sql.connect.service.SparkConnectAddArtifactsHandler","method":"onNext","file":"SparkConnectAddArtifactsHandler.scala","line":42},{"class":"org.sparkproject.connect.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener","method":"onMessage","file":"ServerCalls.java","line":262},{"class":"org.sparkproject.connect.grpc.internal.ServerCallImpl$ServerStreamListenerImpl","method":"messagesAvailableInternal","file":"ServerCallImpl.java","line":334},{"class":"org.sparkproject.connect.grpc.internal.ServerCallImpl$ServerStreamListenerImpl","method":"messagesAvailable","file":"ServerCallImpl.java","line":319},{"class":"org.sparkproject.connect.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable","method":"runInContext","file":"ServerImpl.java","line":834},{"class":"org.sparkproject.connect.grpc.internal.ContextRunnable","method":"run","file":"ContextRunnable.java","line":37},{"class":"org.sparkproject.connect.grpc.internal.SerializingExecutor","method":"run","file":"SerializingExecutor.java","line":133},{"class":"java.util.concurrent.ThreadPoolExecutor","method":"runWorker","file":"ThreadPoolExecutor.java","line":1136},{"class":"java.util.concurrent.ThreadPoolExecutor$Worker","method":"run","file":"ThreadPoolExecutor.java","line":635},{"class":"java.lang.Thread","method":"run","file":"Thread.java","line":840}]},"logger":"SerializingExecutor"}
```

When I simply run case like,

```
scala> spark.sql("SHOW TABLES").schema
org.apache.spark.SparkException: org.sparkproject.io.grpc.StatusRuntimeException: UNKNOWN: Application error processing RPC
  org.apache.spark.sql.connect.client.ArtifactManager.addArtifacts(ArtifactManager.scala:242)
  org.apache.spark.sql.connect.client.ArtifactManager.uploadAllClassFileArtifacts(ArtifactManager.scala:205)
  org.apache.spark.sql.connect.client.SparkConnectClient.execute(SparkConnectClient.scala:121)
  org.apache.spark.sql.SparkSession.$anonfun$sql$3(SparkSession.scala:247)
  org.apache.spark.sql.SparkSession.$anonfun$sql$3$adapted(SparkSession.scala:243)
  org.apache.spark.sql.SparkSession.newDataset(SparkSession.scala:337)
  org.apache.spark.sql.SparkSession.newDataFrame(SparkSession.scala:329)
  org.apache.spark.sql.SparkSession.sql(SparkSession.scala:243)
  org.apache.spark.sql.SparkSession.sql(SparkSession.scala:220)
  org.apache.spark.sql.SparkSession.sql(SparkSession.scala:240)
  ammonite.$sess.cmd6$Helper.<init>(cmd6.sc:1)
  ammonite.$sess.cmd6$.<clinit>(cmd6.sc:7)
```

I believe it suppressed the actual cause

### Why are the changes needed?
bugfix

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

existing tests, (I do not know how to trigger this NPE in UT)
### Was this patch authored or co-authored using generative AI tooling?
no

Closes #49222 from yaooqinn/SPARK-50606.

Authored-by: Kent Yao <yao@apache.org>
Signed-off-by: Kent Yao <yao@apache.org>