[SPARK-45261][CORE] Fix `EventLogFileWriters` to handle `none` as a codec
### What changes were proposed in this pull request?

This PR aims to support `none` as a codec instead of throwing exception.

Currrently, our unit test is supposed to test it, but actually it's not tested at all.

https://github.com/apache/spark/blob/14e5fcf60b4c7f1a797ce4fd54ed66f40445ef70/core/src/test/scala/org/apache/spark/deploy/history/EventLogFileReadersSuite.scala#L120-L124

```
$ build/sbt "core/testOnly *EventLogFileReaderSuite*"
...
[info] - get information, list event log files, zip log files - with codec None (33 milliseconds)
[info] - get information, list event log files, zip log files - with codec Some(lz4) (125 milliseconds)
...
```

### Why are the changes needed?

```
$ bin/spark-shell \
-c spark.eventLog.enabled=true \
-c spark.eventLog.compress=true \
-c spark.eventLog.compression.codec=none
...
23/09/21 13:26:45 ERROR SparkContext: Error initializing SparkContext.
org.apache.spark.SparkIllegalArgumentException: [CODEC_SHORT_NAME_NOT_FOUND] Cannot find a short name for the codec none.
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs with the revised CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #43038 from dongjoon-hyun/SPARK-45261.

Authored-by: Dongjoon Hyun <dhyun@apple.com>
Signed-off-by: Dongjoon Hyun <dhyun@apple.com>