[SPARK-47116][INFRA][R] Install proper Python version in SparkR Windows build to avoid warnings
### What changes were proposed in this pull request?

This PR installs Python 3.11 in SparkR build on Windows.

### Why are the changes needed?

To remove unrelated warnings: (https://github.com/HyukjinKwon/spark/actions/runs/7985005685/job/21802732830
)

```
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "D:\a\spark\spark\python\lib\pyspark.zip\pyspark\__init__.py", line [53](https://github.com/HyukjinKwon/spark/actions/runs/7985005685/job/21802732830#step:10:54), in <module>
  File "D:\a\spark\spark\python\lib\pyspark.zip\pyspark\rdd.py", line [54](https://github.com/HyukjinKwon/spark/actions/runs/7985005685/job/21802732830#step:10:55), in <module>
  File "D:\a\spark\spark\python\lib\pyspark.zip\pyspark\java_gateway.py", line 33, in <module>
  File "D:\a\spark\spark\python\lib\pyspark.zip\pyspark\serializers.py", line 69, in <module>
  File "D:\a\spark\spark\python\lib\pyspark.zip\pyspark\cloudpickle\__init__.py", line 1, in <module>
  File "D:\a\spark\spark\python\lib\pyspark.zip\pyspark\cloudpickle\cloudpickle.py", line 80, in <module>
ImportError: cannot import name 'CellType' from 'types' (C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\types.py)
```

SparkR build does not need Python. However, it shows warnings when the Python version is too low during the attempt to look up Python Data Sources for session initialization. The Windows 2019 runner includes Python 3.7, which Spark does not support. Therefore, we simply install the proper Python for simplicity.

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?

Manually

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #45196 from HyukjinKwon/python-errors.

Authored-by: Hyukjin Kwon <gurwls223@apache.org>
Signed-off-by: Dongjoon Hyun <dhyun@apple.com>