[SPARK-53606][DOCS] Fix MapInPandas/MapInArrow examples with barrier
### What changes were proposed in this pull request?
Fix MapInPandas/MapInArrow examples with barrier

### Why are the changes needed?
the two examples never works:
```
In [4]: df.mapInPandas(filter_func, df.schema, barrier=True).collect()
Out[4]: [Row(id=1, age=21)]

In [5]: df.mapInPandas(filter_func, df.schema, barrier=True).show()
25/09/17 12:36:22 WARN DAGScheduler: Creating new stage failed due to exception - job: 5
org.apache.spark.scheduler.BarrierJobUnsupportedRDDChainException: [SPARK-24820][SPARK-24821]: Barrier execution mode does not allow the following pattern of RDD chain within a barrier stage:
1. Ancestor RDDs that have different number of partitions from the resulting RDD (e.g. union()/coalesce()/first()/take()/PartitionPruningRDD). A workaround for first()/take() can be barrierRdd.collect().head (scala) or barrierRdd.collect()[0] (python).
2. An RDD that depends on multiple barrier RDDs (e.g. barrierRdd1.zip(barrierRdd2)).
	at org.apache.spark.errors.SparkCoreErrors$.barrierStageWithRDDChainPatternError(SparkCoreErrors.scala:231)
	at org.apache.spark.scheduler.DAGScheduler.checkBarrierStageWithRDDChainPattern(DAGScheduler.scala:506)
	at org.apache.spark.scheduler.DAGScheduler.createResultStage(DAGScheduler.scala:656)
	at org.apache.spark.scheduler.DAGScheduler.handleJobSubmitted(DAGScheduler.scala:1342)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3150)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3141)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3130)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:50)

```

### Does this PR introduce _any_ user-facing change?
Doc-only changes

### How was this patch tested?
manually check

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #52365 from zhengruifeng/fix_mapin_barrier.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>