Revert "[SPARK-48591][PYTHON] Simplify the if-else branches with `F.lit`"
revert https://github.com/apache/spark/pull/46946 since it may cause circular import issue
```
  File "/home/jenkins/python/pyspark/sql/connect/functions/__init__.py", line 20, in <module>
    from pyspark.sql.connect.functions.builtin import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenkins/python/pyspark/sql/connect/functions/builtin.py", line 60, in <module>
    from pyspark.sql.connect.udf import _create_py_udf
  File "/home/jenkins/python/pyspark/sql/connect/udf.py", line 38, in <module>
    from pyspark.sql.connect.column import Column
ImportError: cannot import name 'Column' from partially initialized module 'pyspark.sql.connect.column' (most likely due to a circular import) (/home/jenkins/python/pyspark/sql/connect/column.py)
Had test failures in delta.connect.tests.test_deltatable with python; see logs.
```

Closes #46985 from zhengruifeng/revert_simplify_column.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>