[SPARK-46657][INFRA] Install `lxml` in Python 3.12
### What changes were proposed in this pull request?

This PR aims to install `lxml` in Python 3.12.

### Why are the changes needed?

- https://github.com/apache/spark/actions/runs/7476792796/job/20348097114
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/__w/spark/spark/python/pyspark/sql/tests/test_session.py", line 22, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs and daily `Python CI` should pass with Python 3.12.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #44666 from dongjoon-hyun/SPARK-46657.

Authored-by: Dongjoon Hyun <dongjoon@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>