[SPARK-52946][PYTHON] Fix Arrow-optimized Python UDTF to support large var types
### What changes were proposed in this pull request?

Fixes Arrow-optimized Python UDTF to support large var types.

### Why are the changes needed?

The new Arrow-optimized Python UDTF path won't work with large var types.

```py
>>> udtf(returnType="a: string", useArrow=True)
... class TestUDTF:
...     def eval(self, a: int):
...         yield str(a)
...
>>> spark.conf.set("spark.sql.execution.arrow.useLargeVarTypes", True)
>>> TestUDTF(lit(1)).show()
...
pyspark.errors.exceptions.base.PySparkRuntimeError: [RESULT_TYPE_MISMATCH_FOR_ARROW_UDF] Columns do not match in their data type: column 'a' (expected string, actual large_string).
```

### Does this PR introduce _any_ user-facing change?

Yes, the config `spark.sql.execution.arrow.useLargeVarTypes=True` should work in the Arrow-optimized Python UDTF.

### How was this patch tested?

Added the related tests.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #51655 from ueshin/issues/SPARK-52946/use_large_var_types.

Authored-by: Takuya Ueshin <ueshin@databricks.com>
Signed-off-by: Takuya Ueshin <ueshin@databricks.com>