[SPARK-37002][PYTHON] Introduce the 'compute.eager_check' option
### What changes were proposed in this pull request?
Introduce the ```compute.eager_check``` option, with the default value of ```True```.

### Why are the changes needed?
Input validation is a expensive operation, ```compute.eager_check``` is introduced to set whether or not do this operation.

### Does this PR introduce _any_ user-facing change?
```python
>>> ps.get_option('compute.eager_check')
True
>>> ps.set_option('compute.eager_check', False)
>>> ps.get_option('compute.eager_check')
False
>>> ps.set_option('compute.eager_check', 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u02/spark/python/pyspark/pandas/config.py", line 348, in set_option
    _options_dict[key].validate(value)
  File "/u02/spark/python/pyspark/pandas/config.py", line 104, in validate
    raise TypeError(
TypeError: The value for option 'compute.eager_check' was <class 'int'>; however, expected types are [<class 'bool'>].
>>> ps.reset_option('compute.eager_check')
>>> ps.get_option('compute.eager_check')
True
```
### How was this patch tested?
Existing tests

Closes #34281 from dchvn/SPARK-37002.

Authored-by: dch nguyen <dgd_contributor@viettel.com.vn>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>