[SPARK-47555][SQL] Show a warning message about SQLException if `JDBCTableCatalog.loadTable` fails
### What changes were proposed in this pull request?

Record necessary raw exception log when loadTable.

### Why are the changes needed?

The client always told us `Table or view not found`, missing raw exception when load table.

```
bin/spark-shell \
--conf spark.sql.catalog.aaa=org.apache.spark.sql.execution.datasources.v2.jdbc.JDBCTableCatalog \
--conf spark.sql.catalog.aaa.url=jdbc:hive2://ip:abc/data \
--conf spark.sql.catalog.aaa.driver=org.apache.hive.jdbc.HiveDriver
```

```
scala> spark.sql("select count(1) from aaa.data.data_part")
org.apache.spark.sql.AnalysisException: Table or view not found: aaa.data.data_part; line 1 pos 21;
'Aggregate [unresolvedalias(count(1), None)]
+- 'UnresolvedRelation [aaa, data, data_part], [], false

  at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$1(CheckAnalysis.scala:131)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$1$adapted(CheckAnalysis.scala:102)
  at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:367)
  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:366)
  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:366)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  at scala.collection.IterableLike.foreach(IterableLike.scala:74)
  at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
```

### Does this PR introduce _any_ user-facing change?

no.

### How was this patch tested?

Patched
```
scala> spark.sql("select count(1) from aaa.data.data_part")
24/03/26 10:02:37 ERROR JDBCTableCatalog: Failed to load table
org.apache.hive.jdbc.JdbcUriParseException: Bad URL format. Hostname not found  in authority part of the url: ip:abc. Are you missing a '/' after the hostname ?
	at org.apache.hive.jdbc.Utils.configureConnParams(Utils.java:534)
	at org.apache.hive.jdbc.Utils.parseURL(Utils.java:441)
	at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:141)
	at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:107)
	at org.apache.spark.sql.execution.datasources.jdbc.connection.BasicConnectionProvider.getConnection(BasicConnectionProvider.scala:49)
	at org.apache.spark.sql.execution.datasources.jdbc.connection.ConnectionProviderBase.create(ConnectionProvider.scala:102)
```

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #45711 from xleoken/47555.

Authored-by: leo65535 <leo65535@163.com>
Signed-off-by: Dongjoon Hyun <dhyun@apple.com>