[SPARK-37240][SQL] Handle ANSI intervals by `ColumnVectorUtils.populate()`
### What changes were proposed in this pull request?
In the PR, I propose to handle ANSI interval types - `YearMonthIntervalType` and `DayTimeIntervalType` in `ColumnVectorUtils.populate()`.

### Why are the changes needed?
This PR fixes the failure on reading of partitioned parquet files with ANSI interval partition values. The code below demonstrates the issue:
```scala
scala> sql("SELECT INTERVAL '1' YEAR AS i, 0 as id").write.partitionBy("i").parquet("/Users/maximgekk/tmp/ansi_interval_parquet")

scala> spark.read.schema("i INTERVAL YEAR, id INT").parquet("/Users/maximgekk/tmp/ansi_interval_parquet").show(false)
21/11/08 10:56:36 ERROR Executor: Exception in task 0.0 in stage 2.0 (TID 2)
java.lang.RuntimeException: DataType INTERVAL YEAR is not supported in column vectorized reader.
	at org.apache.spark.sql.execution.vectorized.ColumnVectorUtils.populate(ColumnVectorUtils.java:100)
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedParquetRecordReader.initBatch(VectorizedParquetRecordReader.java:243)
```

### Does this PR introduce _any_ user-facing change?
No, this PR fixes the issue above, and the code works as expected after the changes:
```scala
scala> spark.read.schema("i INTERVAL YEAR, id INT").parquet("/Users/maximgekk/tmp/ansi_interval_parquet").show(false)
+---+-----------------+
|id |i                |
+---+-----------------+
|0  |INTERVAL '1' YEAR|
+---+-----------------+
```

### How was this patch tested?
By running the modified test:
```
$ build/sbt "test:testOnly *PartitionedWriteSuite"
```

Closes #34517 from MaxGekk/ansi-interval-as-parquet-part-value.

Authored-by: Max Gekk <max.gekk@gmail.com>
Signed-off-by: Kousuke Saruta <sarutak@oss.nttdata.com>