[SPARK-46998][SQL] Deprecate the SQL config `spark.sql.legacy.allowZeroIndexInFormatString`
### What changes were proposed in this pull request?
In the PR, I propose to deprecate the SQL config `spark.sql.legacy.allowZeroIndexInFormatString` and put it to the list `deprecatedSQLConfigs` in `SQLConf`.

### Why are the changes needed?
After migration on JDK 17+, the SQL config `spark.sql.legacy.allowZeroIndexInFormatString` doesn't work anymore, and doesn't allow to use the zero index. Even users set the config to `true`, they get the error:
```java
Illegal format argument index = 0
java.util.IllegalFormatArgumentIndexException: Illegal format argument index = 0
	at java.base/java.util.Formatter$FormatSpecifier.index(Formatter.java:2808)
	at java.base/java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2879)
```

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
By running the modified test suite:
```
$ build/sbt "test:testOnly *QueryCompilationErrorsSuite"
```

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #45057 from MaxGekk/deprecate-ALLOW_ZERO_INDEX_IN_FORMAT_STRING.

Authored-by: Max Gekk <max.gekk@gmail.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>