[SPARK-43151][DOC] Update the prerequisites for generating Python API docs
### What changes were proposed in this pull request?

Update the prerequisites for generating Python API docs:
* The command should be run under the docs directory so that the input file should be `../dev/requirements.txt`
* Remove `sudo` in the command
* Remove the version for `torch` and `torchvision`. I was getting

```
ERROR: Could not find a version that satisfies the requirement torch==1.13.1 (from versions: 2.0.0)
ERROR: No matching distribution found for torch==1.13.1
ERROR: Could not find a version that satisfies the requirement torchvision==0.14.1
```

### Why are the changes needed?

Update the prerequisites for generating Python API docs, to save troubles from other developers when generating Python Docs.

### Does this PR introduce _any_ user-facing change?

No
### How was this patch tested?

Manually try the command and new requirements.txt

Closes #40804 from gengliangwang/updatePyInstall.

Authored-by: Gengliang Wang <gengliang@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>