[SPARK-47826][SQL][PYTHON][FOLLOW-UP] Do not use list[...] that is invalid type syntax for Python 3.8
### What changes were proposed in this pull request?

This PR is a followup of https://github.com/apache/spark/pull/45826 that proposes to avoid using list[...] that is invalid type syntax for Python 3.8.

### Why are the changes needed?

Python 3.8 support is broken by this https://github.com/apache/spark/actions/runs/8648933358/job/23715458133

```
Starting test(pypy3): pyspark.sql.tests.pandas.test_converter (temp output: /__w/spark/spark/python/target/c6f14f2f-c85c-4336-8023-f5309338dbc5/pypy3__pyspark.sql.tests.pandas.test_converter__h_032d22.log)
Traceback (most recent call last):
  File "/usr/local/pypy/pypy3.8/lib/pypy3.8/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/pypy/pypy3.8/lib/pypy3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/__w/spark/spark/python/pyspark/__init__.py", line 129, in <module>
    from pyspark.sql import SQLContext, HiveContext, Row  # noqa: F401
  File "/__w/spark/spark/python/pyspark/sql/__init__.py", line 42, in <module>
    from pyspark.sql.types import Row, VariantVal
  File "/__w/spark/spark/python/pyspark/sql/types.py", line 51, in <module>
    from pyspark.sql.variant_utils import VariantUtils
  File "/__w/spark/spark/python/pyspark/sql/variant_utils.py", line 26, in <module>
    class VariantUtils:
  File "/__w/spark/spark/python/pyspark/sql/variant_utils.py", line 335, in VariantUtils
    cls, value: bytes, metadata: bytes, pos: int, func: Callable[[list[Tuple[str, int]]], Any]
TypeError: 'type' object is not subscriptable (key typing.Tuple[str, int])
```

### Does this PR introduce _any_ user-facing change?

### How was this patch tested?

Manually tested.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #46044 from HyukjinKwon/SPARK-47366-followup.

Authored-by: Hyukjin Kwon <gurwls223@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>