[SPARK-44079][SQL] Fix `ArrayIndexOutOfBoundsException` when parse array as struct using PERMISSIVE mode with corrupt record
### What changes were proposed in this pull request?
When use PERMISSIVE mode to parse json array as structs with `_corrupt_record`. The error will be reported.
```scala
val data = """[{"a": "incorrect", "b": "correct"}, {"a": "incorrect", "b": "correct"}]"""
val schema = new StructType(Array(StructField("a", IntegerType),
  StructField("b", StringType), StructField("_corrupt_record", StringType)))

spark.read.option("mode", "PERMISSIVE").option("multiline", "true").schema(schema)
  .json(Seq(data).toDS()).show()

// error
org.apache.spark.SparkException: Job aborted due to stage failure: Task 4 in stage 2.0 failed 1 times, most recent failure: Lost task 4.0 in stage 2.0 (TID 9) (charlottesmbp2.home executor driver): java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.genericGet(rows.scala:201)
        at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow.getAs(rows.scala:35)
        at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow.get(rows.scala:37)
        at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow.get$(rows.scala:37)
        at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.get(rows.scala:195)
```
The `JacksonParser` wrap row list as a new `InternalRow`. So `FailureSafeParser` can't parse it normally when `_corrupt_record` is defined.
This PR to make sure `BadRecordException` can cover row list parsed by a string record. Then the `FailureSafeParser` can handle row list one by one.

### Why are the changes needed?
Fix the bug when parse array as struct using PERMISSIVE mode with corrupt record

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
add new test.

Closes #41662 from Hisoka-X/SPARK-44079_array_as_structs_corrput_record.

Authored-by: Jia Fan <fanjiaeminem@qq.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>