[SPARK-53531][CORE] Better error message for HadoopRDD.getInputFormat
### What changes were proposed in this pull request?

When `HadoopRDD.getInputFormat` fails to initialize the InputFormat, the thrown error message is not clear. This PR enhances the exception message to include the class name of InputFormat.

A typical case that triggers this issue is reading an Iceberg table without a properly configured Iceberg catalog.

https://stackoverflow.com/questions/72620351/getting-error-when-querying-iceberg-table-via-spark-thrift-server-using-beeline

### Why are the changes needed?

Improve the error message.

### Does this PR introduce _any_ user-facing change?

Yes, the user would know more info from the error message.

### How was this patch tested?

Before
```
spark-sql (default)> select * from i;
2025-09-09 05:52:13 ERROR SparkSQLDriver: Failed in [select * from i]
java.lang.RuntimeException: java.lang.InstantiationException
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:157)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:126)
	at org.apache.spark.rdd.HadoopRDD.getInputFormat(HadoopRDD.scala:219)
	at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:233)
	at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:301)
	...
Caused by: java.lang.InstantiationException
	at java.base/jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:155)
	... 67 more
```

After
```
spark-sql (default)> select * from i;
2025-09-09 06:23:48 ERROR SparkSQLDriver: Failed in [select * from i]
java.lang.RuntimeException: Failed to instantiate org.apache.hadoop.mapred.FileInputFormat
	at org.apache.spark.rdd.HadoopRDD.getInputFormat(HadoopRDD.scala:223)
	at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:231)
	at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:301)
	...
Caused by: java.lang.InstantiationException
	at java.base/jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:155)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:126)
	at org.apache.spark.rdd.HadoopRDD.getInputFormat(HadoopRDD.scala:218)
	... 65 more
```

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #52282 from pan3793/SPARK-53531.

Authored-by: Cheng Pan <chengpan@apache.org>
Signed-off-by: yangjie01 <yangjie01@baidu.com>