[SPARK-51065][SQL] Disallowing non-nullable schema when Avro encoding is used for TransformWithState
### What changes were proposed in this pull request?
Right now, effectively set all fields in a schema to nullable, regardless of what the user specifies.
- However, when Avro encoding is used, we want to enforce nullability in order to enable the schema evolution cases we support.
- Nullability can only be set by the user in Python, so when non-nullable fields are defined, we throw an error
- In Scala, Encoders.product set fields to non-nullable by default (user cannot configure this), so we turn the fields to nullable

### Why are the changes needed?

In order to keep parity with the user-specified schema with the actual schema that we use, and to enable the schema evolution use cases we want

### Does this PR introduce _any_ user-facing change?

This error is thrown if the schema is defined as non-nullable
```
Traceback (most recent call last):
  File "/Users/eric.marnadi/spark/python/pyspark/sql/tests/pandas/test_pandas_transform_with_state.py", line 1496, in test_not_nullable_fails
    self._run_evolution_test(
  File "/Users/eric.marnadi/spark/python/pyspark/sql/tests/pandas/test_pandas_transform_with_state.py", line 1344, in _run_evolution_test
    q.processAllAvailable()
  File "/Users/eric.marnadi/spark/python/pyspark/sql/streaming/query.py", line 351, in processAllAvailable
    return self._jsq.processAllAvailable()
  File "/Users/eric.marnadi/spark/python/lib/py4j-0.10.9.9-src.zip/py4j/java_gateway.py", line 1362, in __call__
    return_value = get_return_value(
  File "/Users/eric.marnadi/spark/python/pyspark/errors/exceptions/captured.py", line 258, in deco
    raise converted from None
pyspark.errors.exceptions.captured.StreamingQueryException: [STREAM_FAILED] Query [id = 541c5df0-24e4-4702-b87a-c4edfb6a952c, runId = 4259c7b9-3846-4f73-9204-c3d71b07018c] terminated with exception: [STATE_STORE_SCHEMA_MUST_BE_NULLABLE] If schema evolution is enabled, all the fields in the schema for column family state must be nullable.
Please set the 'spark.sql.streaming.stateStore.encodingFormat' to 'UnsafeRow' or make the schema nullable.
Current schema: StructType(StructField(id,IntegerType,false),StructField(name,StringType,false)) SQLSTATE: XXKST SQLSTATE: XXKST
=== Streaming Query ===
Identifier: evolution_test [id = 541c5df0-24e4-4702-b87a-c4edfb6a952c, runId = 4259c7b9-3846-4f73-9204-c3d71b07018c]
Current Committed Offsets: {}
Current
```

### How was this patch tested?

Unit tests

### Was this patch authored or co-authored using generative AI tooling?

No

Closes #49751 from ericm-db/disallow-non-nullable-schema.

Authored-by: Eric Marnadi <eric.marnadi@databricks.com>
Signed-off-by: Jungtaek Lim <kabhwan.opensource@gmail.com>
(cherry picked from commit 2eeeae325f6b49776da9c2d47d3af43453ca9225)
Signed-off-by: Jungtaek Lim <kabhwan.opensource@gmail.com>