[SPARK-45674][CONNECT][PYTHON] Improve error message for JVM-dependent attributes on Spark Connect
### What changes were proposed in this pull request?

This PR proposes to improve error message for JVM-dependent attributes on Spark Connect.

### Why are the changes needed?

To improve the usability of error message by using proper error class.

### Does this PR introduce _any_ user-facing change?

No API change, but only user-facing error messages are improved as below:

**Before**
```
>>> spark.sparkContext
PySparkNotImplementedError: [NOT_IMPLEMENTED] sparkContext() is not implemented.
```
**After**
```
>>> spark.sparkContext
PySparkAttributeError: [JVM_ATTRIBUTE_NOT_SUPPORTED] Attribute `sparkContext` is not supported in Spark Connect as it depends on the JVM. If you need to use this attribute, do not use Spark Connect when creating your session.
```

### How was this patch tested?

The existing CI should pass

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #43537 from itholic/SPARK-45674.

Authored-by: Haejoon Lee <haejoon.lee@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>