[SPARK-42269][CONNECT][PYTHON] Support complex return types in DDL strings
### What changes were proposed in this pull request?
Support complex return types in DDL strings.

### Why are the changes needed?
Parity with vanilla PySpark.

### Does this PR introduce _any_ user-facing change?
Yes.

```py
# BEFORE
>>> spark.range(2).select(udf(lambda x: (x, x), "struct<x:integer, y:integer>")("id"))
...
AssertionError: returnType should be singular

>>> spark.udf.register('f', lambda x: (x, x), "struct<x:integer, y:integer>")
...
AssertionError: returnType should be singular

# AFTER
>>> spark.range(2).select(udf(lambda x: (x, x), "struct<x:integer, y:integer>")("id"))
DataFrame[<lambda>(id): struct<x:int,y:int>]

>>> spark.udf.register('f', lambda x: (x, x), "struct<x:integer, y:integer>")
<function <lambda> at 0x7faee0eaaca0>

```

### How was this patch tested?
Unit tests.

Closes #39964 from xinrong-meng/collection_ret_type.

Authored-by: Xinrong Meng <xinrong@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>