[SPARK-51590][SQL] Disable TIME in builtin file-based datasources
### What changes were proposed in this pull request?
In the PR, I propose to modify the `supportDataType()` method of builtin file based datasources, and disable the new data type `TIME` till it is fully supported in such datasources. In particular, disable it in the following V1 and V2 datasources:
- Text
- JSON/CSV
- XML
- Parquet
- ORC: native and Hive
- Avro

### Why are the changes needed?
Before the changes if we don't disable the unsupported data type `TIME` in datasources, users might get exceptions from external libs like:

ORC:
```java
java.lang.IllegalArgumentException: Can't parse category at 'time^(6)'
	at org.apache.orc.impl.ParserUtils.parseCategory(ParserUtils.java:67)
```

Avro:
```java
org.apache.spark.sql.avro.IncompatibleSchemaException: Unexpected type TimeType(6).
	at org.apache.spark.sql.avro.SchemaConverters$.toAvroType(SchemaConverters.scala:369)
```

### Does this PR introduce _any_ user-facing change?
Yes. After the changes, users get more friendly `AnalysisException`:
```
[UNSUPPORTED_DATA_TYPE_FOR_DATASOURCE] The ORC datasource doesn't support the column `t` of the type "TIME(6)". SQLSTATE: 0A000
```

### How was this patch tested?
By running the modified test suites:
```
$ build/sbt "test:testOnly *FileBasedDataSourceSuite"
$ build/sbt -Phive "test:testOnle *HiveOrcQuerySuite"
```

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #50358 from MaxGekk/time-off-fs-ds-2.

Authored-by: Max Gekk <max.gekk@gmail.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>