[SPARK-41694][CORE] Isolate RocksDB path for Live UI and automatically cleanup when `SparkContext.stop()`
### What changes were proposed in this pull request?
This pr brings two fixes：

- Add sub-dir with `spark-ui` prefix under `spark.ui.store.path` for each Spark App to ensure that multiple Spark Apps can run normally use the same Spark Client with same `spark.ui.store.path` configuration

- Automatically cleanup Live UI data when `SparkContext.stop()`

### Why are the changes needed?
There are 2 issue before this pr:

1.  Multiple Spark Apps can't run normally use the same Spark Client with same `spark.ui.store.path` configuration, the following exceptions will occur:

```
org.rocksdb.RocksDBException: While lock file: /${baseDir}/listing.rdb/LOCK: Resource temporarily unavailable
```

At the same time, only one Spark App can run normally use RocksDB as the Live UI store.

After this pr, each Spark App uses an independent RocksDB directory when  `spark.ui.store.path` is specified as Live UI store.

2.  `spark.ui.store.path` directory not clean up when `SparkContext.stop()`:
   - The disk space occupied by the `spark.ui.store.path` directory will continue to grow.
   - When submitting new App and reusing the `spark.ui.store.path` directory, we will see the content related to the previous App, which is a bit strange

After this pr, `spark.ui.store.path` directory is is automatically cleaned by default when `SparkContext` stop.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Add new UTs

Closes #39226 from LuciferYang/SPARK-41694.

Lead-authored-by: yangjie01 <yangjie01@baidu.com>
Co-authored-by: YangJie <yangjie01@baidu.com>
Co-authored-by: Gengliang Wang <gengliang@apache.org>
Signed-off-by: Gengliang Wang <gengliang@apache.org>