[SPARK-50560][SQL] Improve type coercion and boundary checking for RANDSTR SQL function
### What changes were proposed in this pull request?

This PR improve type coercion and boundary checking for RANDSTR SQL function.

srielau found the following issues and wrote them down in SPARK-50560:
* TINYINT and BIGINT were not supported.
* No type coercion from floating-point numbers was implemented.
* No explicit error checking for negative numbers was implemented, resulting in weird stacktraces instead.

### Why are the changes needed?

This PR fixes the above problems to make the function work in more cases and produce better error messages when it fails.

For example:

```
SELECT randstr(CAST(10 AS TINYINT), 0) AS result
> ceV0PXaR2I

SELECT randstr(CAST(10 AS BIGINT), 0) AS result
> ceV0PXaR2I

SELECT randstr(1.0F, 0) AS result
> c

SELECT randstr(1.0D, 0) AS result
> c

SELECT randstr(-1, 0) AS result
> Error: The RANDSTR function desired string length must be positive or zero. Please provide an updated string length and then retry the query or command again.
```

### Does this PR introduce _any_ user-facing change?

Yes, see above.

### How was this patch tested?

This PR adds golden file based test coverage, and updates existing coverage.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #49210 from dtenedor/fix-randstr-types.

Lead-authored-by: Daniel Tenedorio <daniel.tenedorio@databricks.com>
Co-authored-by: Wenchen Fan <cloud0fan@gmail.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>