[SPARK-38986][SQL] Prepend error class tag to error messages
### What changes were proposed in this pull request?
In the PR, I propose to prepend the error class tag to error messages. The `SparkThrowableHelper.getMessage()` method was modified for this purpose:
```scala
def getMessage(errorClass: String, messageParameters: Array[String]): String = {
  ...
    "[" + errorClass + "] " + String.format ...
  }
```

Other changes are related to tests where the expected error messages were extended by error class tags. Also I introduced new base trait `QueryErrorsSuiteBase` for test suites w/ two helper methods:
```scala
  def checkErrorClass(
      exception: Exception with SparkThrowable,
      errorClass: String,
      msg: String,
      sqlState: Option[String] = None,
      matchMsg: Boolean = false): Unit

  def validateParsingError(
      sqlText: String,
      errorClass: String,
      sqlState: String,
      message: String): Unit
```
The methods are supposed to be used in `QueryParsingErrorsSuite`, `QueryCompilationErrorsSuite`, `QueryExecutionErrorsSuite` and so on, to check error classes, messages, and sqlStates.

### Why are the changes needed?
The error class tags will be used as unique identifiers to google issues, and refer to Spark docs.

### Does this PR introduce _any_ user-facing change?
Yes, the PR changes user-facing error messages.

### How was this patch tested?
By running the modified test suites:
```
$ build/sbt "sql/testOnly *QueryExecutionErrorsSuite"
$ build/sbt "test:testOnly *QueryCompilationErrorsSuite"
$ build/sbt "test:testOnly *QueryCompilationErrorsDSv2Suite"
$ build/sbt "testOnly *QueryParsingErrorsSuite"
$ build/sbt "sql/testOnly *SQLQueryTestSuite"
```

Closes #36287 from MaxGekk/output-error-class-tag.

Authored-by: Max Gekk <max.gekk@gmail.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>