[SPARK-41558][PYTHON][TESTS] Disable Coverage in python.pyspark.tests.test_memory_profiler
### What changes were proposed in this pull request?

This PR is a followup of https://github.com/apache/spark/pull/38677 that disables Coverage in their tests for now.

### Why are the changes needed?

To recover the coverage. These tests look consistently failing:

https://github.com/apache/spark/actions/runs/3712125552/jobs/6293347848

```
======================================================================
FAIL [13.173s]: test_memory_profiler (pyspark.tests.test_memory_profiler.MemoryProfilerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/spark/spark/python/pyspark/tests/test_memory_profiler.py", line 56, in test_memory_profiler
    self.assertTrue("plus_one" in fake_out.getvalue())
AssertionError: False is not true

======================================================================
FAIL [3.986s]: test_profile_pandas_function_api (pyspark.tests.test_memory_profiler.MemoryProfilerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/spark/spark/python/pyspark/tests/test_memory_profiler.py", line 87, in test_profile_pandas_function_api
    self.assertTrue(f_name in fake_out.getvalue())
AssertionError: False is not true

======================================================================
FAIL [3.722s]: test_profile_pandas_udf (pyspark.tests.test_memory_profiler.MemoryProfilerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/spark/spark/python/pyspark/tests/test_memory_profiler.py", line 69, in test_profile_pandas_udf
    self.assertTrue(f_name in fake_out.getvalue())
AssertionError: False is not true

----------------------------------------------------------------------
Ran 3 tests in 20.882s
```

### Does this PR introduce _any_ user-facing change?

No, test-only

### How was this patch tested?

Manual tests.

Closes #39106 from HyukjinKwon/SPARK-41558.

Authored-by: Hyukjin Kwon <gurwls223@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>