[SPARK-46461][BUILD] Clean up unavailable `SQL/Hive console settings` from SparkBuild.scala
### What changes were proposed in this pull request?
This pr clean up unavailable `SQL/Hive console settings` from `SparkBuild.scala`

### Why are the changes needed?
This is a broken dev feature. When we execute `build/sbt "sql/console"` or `build/sbt "hive/console" -Phive`, we encounter the following error:

```
Welcome to Scala 2.13.15 (OpenJDK 64-Bit Server VM, Java 17.0.12).
Type in expressions for evaluation. Or try :help.
       import org.apache.spark.sql.catalyst.errors._
                                            ^
On line 6: error: object errors is not a member of package org.apache.spark.sql.catalyst
       import org.apache.spark.sql.catalyst.analysis._
                                                     ^
On line 4: error: Unused import
       Applicable -Wconf / nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=
       import org.apache.spark.sql.catalyst.dsl._
                                                ^
On line 5: error: Unused import
       Applicable -Wconf / nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=
       import org.apache.spark.sql.catalyst.errors._
                                                   ^
On line 6: error: Unused import
       Applicable -Wconf / nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=
       import org.apache.spark.sql.catalyst.expressions._
                                                        ^
On line 7: error: Unused import
       Applicable -Wconf / nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=
       import org.apache.spark.sql.catalyst.plans.logical._
                                                          ^
On line 8: error: Unused import
       Applicable -Wconf / nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=
       import org.apache.spark.sql.catalyst.rules._
                                                  ^
On line 9: error: Unused import
       Applicable -Wconf / nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=
       import org.apache.spark.sql.catalyst.util._
                                                 ^
On line 10: error: Unused import
       Applicable -Wconf / nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=
       import org.apache.spark.sql.execution
                                   ^
On line 11: error: Unused import
       Applicable -Wconf / nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=
       import org.apache.spark.sql.functions._
                                             ^
On line 12: error: Unused import
       Applicable -Wconf / nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=
       import org.apache.spark.sql.types._
                                         ^
On line 13: error: Unused import
       Applicable -Wconf / nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=
       import sqlContext.implicits._
                                   ^
On line 17: error: Unused import
       Applicable -Wconf / nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=
       import sqlContext._
                         ^
On line 18: error: Unused import
       Applicable -Wconf / nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=

Failed to initialize compiler: NoSuchMethodError.
This is most often remedied by a full clean and recompile.
Otherwise, your classpath may continue bytecode compiled by
different and incompatible versions of scala.

java.lang.NoSuchMethodError: 'org.jline.utils.AttributedString org.jline.utils.AttributedString.fromAnsi(java.lang.String, java.util.List, java.lang.String, java.lang.String)'
	at org.jline.reader.impl.LineReaderImpl.fromAnsi(LineReaderImpl.java:4236)
	at org.jline.reader.impl.LineReaderImpl.expandPromptPattern(LineReaderImpl.java:4158)
	at org.jline.reader.impl.LineReaderImpl.setPrompt(LineReaderImpl.java:1260)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:628)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:512)
	at scala.tools.nsc.interpreter.jline.Reader.readOneLine(Reader.scala:43)
	at scala.tools.nsc.interpreter.shell.InteractiveReader.readLine(InteractiveReader.scala:38)
	at scala.tools.nsc.interpreter.shell.InteractiveReader.readLine$(InteractiveReader.scala:38)
	at scala.tools.nsc.interpreter.jline.Reader.readLine(Reader.scala:33)
	at scala.tools.nsc.interpreter.shell.ILoop.readOneLine(ILoop.scala:455)
	at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:460)
	at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:993)
	at xsbt.ConsoleBridge.run(ConsoleBridge.scala:78)
	at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:208)
	at sbt.Console.console0$1(Console.scala:65)
	at sbt.Console.$anonfun$apply$5(Console.scala:75)
	at sbt.Run$.executeSuccess(Run.scala:187)
	at sbt.Console.$anonfun$apply$4(Console.scala:75)
	at sbt.internal.util.Terminal.withRawInput(Terminal.scala:146)
	at sbt.internal.util.Terminal.withRawInput$(Terminal.scala:144)
	at sbt.internal.util.Terminal$ProxyTerminal$.withRawInput(Terminal.scala:424)
	at sbt.Console.$anonfun$apply$3(Console.scala:75)
	at sbt.internal.util.Terminal$TerminalImpl.withRawOutput(Terminal.scala:1028)
	at sbt.internal.util.Terminal$ProxyTerminal$.withRawOutput(Terminal.scala:463)
	at sbt.Console.apply(Console.scala:72)
	at sbt.Console.apply(Console.scala:50)
	at sbt.Console.apply(Console.scala:42)
	at sbt.Defaults$.$anonfun$consoleTask$1(Defaults.scala:2235)
	at sbt.Defaults$.$anonfun$consoleTask$1$adapted(Defaults.scala:2221)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
	at sbt.Execute.work(Execute.scala:292)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
       ^
       error: not found: value sc
```

This appears to be a feature that has been unusable for a long time (I think there should be no developers still using it), and from the code, some imported packages, such as `org.apache.spark.sql.catalyst.errors`, no longer exist in Spark now.

On the other hand, we can fulfill similar development and debugging needs by executing

```
build/sbt clean package -Phive -Phive -Phive-thriftserver
export SPARK_PREPEND_CLASSES=true
bin/spark-shell

or

bin/spark-sql
```

So, this pr cleans up these unusable settings instead of fixing them.

### Does this PR introduce _any_ user-facing change?
No, just for dev.

### How was this patch tested?
Pass GitHub Actions

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #48635 from LuciferYang/cleanup-console-setting.

Lead-authored-by: yangjie01 <yangjie01@baidu.com>
Co-authored-by: YangJie <yangjie01@baidu.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>