[SPARK-53390][PS] Raise error when bools with None `astype` to ints under ANSI
### What changes were proposed in this pull request?
- Raise error when bools with None `astype` to ints under ANSI, to match native pandas behavior:
```py
>>> pd.Series([True, None]).astype(int)
Traceback (most recent call last):
...
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```
- Improve tests

### Why are the changes needed?
Part of https://issues.apache.org/jira/browse/SPARK-53389

### Does this PR introduce _any_ user-facing change?
No the feature isn't released.

```py
>>> psser = ps.Series([True, None])
```
From
```py
>>> psser.astype(int)
0    1.0
1    NaN
dtype: float64
```

To
```py
>>> psser.astype(int)
...
ValueError: Cannot convert bools with missing values to integer
```

### How was this patch tested?
Commands below pass

```
SPARK_ANSI_SQL_MODE=true ./python/run-tests --python-executables=python3.11 --testnames "pyspark.pandas.tests.data_type_ops.test_as_type AsTypeTests.test_astype"

SPARK_ANSI_SQL_MODE=false ./python/run-tests --python-executables=python3.11 --testnames "pyspark.pandas.tests.data_type_ops.test_as_type AsTypeTests.test_astype"

SPARK_ANSI_SQL_MODE=true ./python/run-tests --python-executables=python3.11 --testnames "pyspark.pandas.tests.series.test_as_type SeriesAsTypeTests.test_astype"

SPARK_ANSI_SQL_MODE=false ./python/run-tests --python-executables=python3.11 --testnames "pyspark.pandas.tests.series.test_as_type SeriesAsTypeTests.test_astype"
```

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #52133 from xinrong-meng/test_astype.

Authored-by: Xinrong Meng <xinrong@apache.org>
Signed-off-by: Xinrong Meng <xinrong@apache.org>