[SPARK-48723][INFRA] Run `git cherry-pick --abort` if backporting is denied by committer
### What changes were proposed in this pull request?

This pull request includes the addition of `git cherry-pick --abort` to run if backporting is denied by committers.

Otherwise, the unresolved cherry-pick context will block following command to be run properly

```python
Error cherry-picking: Command '['git', 'cherry-pick', '-sx', '3d460991']' returned non-zero exit status 1.
y fix-up this merge? (y/N): n
Okay, exiting
Restoring head pointer to master
git checkout master
error: you need to resolve your current index first
Restoring head pointer to master
git checkout master
error: you need to resolve your current index first
Traceback (most recent call last):
  File "/Users/hzyaoqin/spark/./dev/merge_spark_pr.py", line 234, in cherry_pick

  File "/Users/hzyaoqin/spark/./dev/merge_spark_pr.py", line 118, in run_cmd

  File "/opt/homebrew/Cellar/python3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Why are the changes needed?

improve merge PR progress

### Does this PR introduce _any_ user-facing change?

no
### How was this patch tested?

Locally with python interpreter:
```python
>>> cherry_pick(47082, "3d46099", "branch-3.5")
Enter a branch name [branch-3.5]:
git fetch apache branch-3.5:PR_TOOL_PICK_PR_47082_BRANCH-3.5
From github.com:apache/spark
 * [new branch]              branch-3.5 -> PR_TOOL_PICK_PR_47082_BRANCH-3.5
git checkout PR_TOOL_PICK_PR_47082_BRANCH-3.5
Updating files: 100% (6027/6027), done.
Switched to branch 'PR_TOOL_PICK_PR_47082_BRANCH-3.5'
git cherry-pick -sx 3d46099
error: could not apply 3d460991ce7... [SPARK-48709][SQL] Fix varchar type resolution mismatch for DataSourceV2 CTAS
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
Error cherry-picking: Command '['git', 'cherry-pick', '-sx', '3d46099']' returned non-zero exit status 1.
 fix-up this merge? (y/N): n
git cherry-pick --abort
Okay, exiting
```

### Was this patch authored or co-authored using generative AI tooling?

no

Closes #47101 from yaooqinn/SPARK-48723.

Authored-by: Kent Yao <yao@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>