[SPARK-44525][SQL] Improve error message when Invoke method is not found
### What changes were proposed in this pull request?

This PR aims to improve the error message when `Invoke`'s `method` is not found.

### Why are the changes needed?

Currently, the error message is not clear when `Invoke`'s `method` is not found.

There is one error message I have encountered, which is not much helpful to find the root cause.
```
org.apache.spark.SparkException: [INTERNAL_ERROR] A method named "invoke" is not declared in any enclosing class nor any supertype
	at org.apache.spark.SparkException$.internalError(SparkException.scala:77)
	at org.apache.spark.SparkException$.internalError(SparkException.scala:81)
	at org.apache.spark.sql.errors.QueryExecutionErrors$.methodNotDeclaredError(QueryExecutionErrors.scala:452)
	at org.apache.spark.sql.catalyst.expressions.objects.InvokeLike.findMethod(objects.scala:173)
	at org.apache.spark.sql.catalyst.expressions.objects.InvokeLike.findMethod$(objects.scala:170)
	at org.apache.spark.sql.catalyst.expressions.objects.Invoke.findMethod(objects.scala:363)
	at org.apache.spark.sql.catalyst.expressions.objects.Invoke.method$lzycompute(objects.scala:391)
	at org.apache.spark.sql.catalyst.expressions.objects.Invoke.method(objects.scala:389)
	at org.apache.spark.sql.catalyst.expressions.objects.Invoke.eval(objects.scala:401)
	at org.apache.spark.sql.catalyst.expressions.HashExpression.eval(hash.scala:292)
	at org.apache.spark.sql.catalyst.expressions.Pmod.eval(arithmetic.scala:1054)
```

### Does this PR introduce _any_ user-facing change?

Yes, Spark returns a more clear error message.

### How was this patch tested?

Add UT.

Closes #42128 from pan3793/SPARK-44525.

Authored-by: Cheng Pan <chengpan@apache.org>
Signed-off-by: yangjie01 <yangjie01@baidu.com>