[SPARK-39109][PYTHON] Adjust `GroupBy.mean/median` to match pandas 1.4
### What changes were proposed in this pull request?
The PR is proposed to
- Implement `numeric_only` of `SeriesGroupBy.mean` and `DataFrameGroupBy.mean`
- Adjust `SeriesGroupBy.mean/median` to match pandas 1.4

### Why are the changes needed?
Improve API compatibility with pandas.

### Does this PR introduce _any_ user-facing change?
Yes. `GroupBy.mean/median` behaves the same as pandas 1.4's.

Take `GroupBy.mean` as an example:
- DataFrameGroupBy.mean
```py
>>> psdf = ps.DataFrame({"A": [1, 2, 1, 2],"B": [3.1, 4.1, 4.1, 3.1],"C": ["a", "b", "b", "a"],"D": [True, False, False, True]})
>>> psdf
   A    B  C      D
0  1  3.1  a   True
1  2  4.1  b  False
2  1  4.1  b  False
3  2  3.1  a   True

>>> psdf.groupby('A').mean(numeric_only=False)
...: FutureWarning: Dropping invalid columns in GroupBy.mean is deprecated. In a future version, a TypeError will be raised. Before calling .mean, select only columns which should be valid for the function.
  warnings.warn(
     B    D
A
1  3.6  0.5
2  3.6  0.5

>>> psdf.groupby('A').mean(numeric_only=None)
...: FutureWarning: Dropping invalid columns in GroupBy.mean is deprecated. In a future version, a TypeError will be raised. Before calling .mean, select only columns which should be valid for the function.
  warnings.warn(
     B    D
A
1  3.6  0.5
2  3.6  0.5

>>> psdf.groupby('A').mean(numeric_only=True)
     B    D
A
1  3.6  0.5
2  3.6  0.5

# Not raise the FutureWarning when there is no non-numeric aggregation column
>>> psdf[['A', 'B', 'D']].groupby('A').mean(numeric_only=False)
     B    D
A
1  3.6  0.5
2  3.6  0.5
```
- SeriesGroupBy.mean
```py
>>> psdf.groupby("A")["C"].mean()
Traceback (most recent call last):
...
TypeError: Only numeric aggregation column is accepted.
```
### How was this patch tested?
Unit tests.

Closes #36452 from xinrong-databricks/groupby.numeric_only.

Authored-by: Xinrong Meng <xinrong.meng@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>