[SPARK-51558][BUILD][INFRA] Automatically set env `OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` when testing on macOS
### What changes were proposed in this pull request?
This pr aims to automatically set the environment variable `OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` when conducting tests on macOS to avoid:

```
objc[1065]: +[NSMutableString initialize] may have been in progress in another thread when fork() was called.
objc[1065]: +[NSMutableString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

### Why are the changes needed?
Although we can manually export `OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` before running the tests, this current PR simplifies that process.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
- Pass GitHub Actions
- Maven test on ubuntu: https://github.com/LuciferYang/spark/runs/39048703678

![image](https://github.com/user-attachments/assets/53f5edb5-0bf5-4d9e-9ffa-11e9ee015c1c)

- Maven test on macOS: https://github.com/LuciferYang/spark/actions/runs/13950550715

![image](https://github.com/user-attachments/assets/70927ac4-944c-409f-a97c-5e7980d93f43)

- local testing on macOS 15.3.2 (24D81):

```
python3 --version
Python 3.11.1
```

**SBT**

```
 build/sbt clean "sql/testOnly org.apache.spark.sql.execution.python.PythonDataSourceSuite"
```

Before

```
...
22:52:09.861 WARN org.apache.spark.sql.execution.datasources.DataSourceManager: The data source SimpleDataSource replaced a previously registered data source.
objc[1065]: +[NSMutableString initialize] may have been in progress in another thread when fork() was called.
objc[1065]: +[NSMutableString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
[info] - SPARK-46568: case insensitive options *** FAILED *** (388 milliseconds)
[info]   org.apache.spark.SparkException: Python worker exited unexpectedly (crashed). Consider setting 'spark.sql.execution.pyspark.udf.faulthandler.enabled' or'spark.python.worker.faulthandler.enabled' configuration to 'true' for the better Python traceback.
[info]   at org.apache.spark.sql.execution.python.PythonPlannerRunner.runInPython(PythonPlannerRunner.scala:147)
[info]   at org.apache.spark.sql.execution.datasources.v2.python.UserDefinedPythonDataSource.createWriteInfoInPython(UserDefinedPythonDataSource.scala:94)
...
[info]   Cause: java.io.EOFException:
[info]   at java.base/java.io.DataInputStream.readInt(DataInputStream.java:386)
[info]   at org.apache.spark.sql.execution.datasources.v2.python.UserDefinedPythonDataSourceWriteRunner.receiveFromPython(UserDefinedPythonDataSource.scala:419)
[info]   at org.apache.spark.sql.execution.datasources.v2.python.UserDefinedPythonDataSourceWriteRunner.receiveFromPython(UserDefinedPythonDataSource.scala:379)
[info]   at org.apache.spark.sql.execution.python.PythonPlannerRunner.runInPython(PythonPlannerRunner.scala:120)
[info]   at org.apache.spark.sql.execution.datasources.v2.python.UserDefinedPythonDataSource.createWriteInfoInPython(UserDefinedPythonDataSource.scala:94)
[info]   at org.apache.spark.sql.execution.datasources.v2.python.PythonBatchWrite.createBatchWriterFactory(PythonWrite.scala:67)
[info]   at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.writeWithV2(WriteToDataSourceV2Exec.scala:408)
...
[info] Run completed in 13 seconds, 883 milliseconds.
[info] Total number of tests run: 22
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 17, failed 5, canceled 0, ignored 0, pending 0
[info] *** 5 TESTS FAILED ***
```

After

```
[info] Run completed in 16 seconds, 384 milliseconds.
[info] Total number of tests run: 22
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 22, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
```

**Maven**

```
build/mvn clean install -pl sql/core -am  -Dtest=none -DwildcardSuites=org.apache.spark.sql.execution.python.PythonDataSourceSuite
```

before

```
...
objc[96334]: +[NSMutableString initialize] may have been in progress in another thread when fork() was called.
objc[96334]: +[NSMutableString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
- SPARK-46568: case insensitive options *** FAILED ***
  org.apache.spark.SparkException: Python worker exited unexpectedly (crashed). Consider setting 'spark.sql.execution.pyspark.udf.faulthandler.enabled' or'spark.python.worker.faulthandler.enabled' configuration to 'true' for the better Python traceback.
  at org.apache.spark.sql.execution.python.PythonPlannerRunner.runInPython(PythonPlannerRunner.scala:147)
  at org.apache.spark.sql.execution.datasources.v2.python.UserDefinedPythonDataSource.createWriteInfoInPython(UserDefinedPythonDataSource.scala:94)
  at org.apache.spark.sql.execution.datasources.v2.python.PythonBatchWrite.createBatchWriterFactory(PythonWrite.scala:67)
  at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.writeWithV2(WriteToDataSourceV2Exec.scala:408)
  at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.writeWithV2$(WriteToDataSourceV2Exec.scala:394)
  at org.apache.spark.sql.execution.datasources.v2.AppendDataExec.writeWithV2(WriteToDataSourceV2Exec.scala:237)
  at org.apache.spark.sql.execution.datasources.v2.V2ExistingTableWriteExec.run(WriteToDataSourceV2Exec.scala:359)
  at org.apache.spark.sql.execution.datasources.v2.V2ExistingTableWriteExec.run$(WriteToDataSourceV2Exec.scala:358)
  at org.apache.spark.sql.execution.datasources.v2.AppendDataExec.run(WriteToDataSourceV2Exec.scala:237)
  at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
  ...
  Cause: java.io.EOFException:
  at java.base/java.io.DataInputStream.readInt(DataInputStream.java:386)
  at org.apache.spark.sql.execution.datasources.v2.python.UserDefinedPythonDataSourceWriteRunner.receiveFromPython(UserDefinedPythonDataSource.scala:419)
  at org.apache.spark.sql.execution.datasources.v2.python.UserDefinedPythonDataSourceWriteRunner.receiveFromPython(UserDefinedPythonDataSource.scala:379)
  at org.apache.spark.sql.execution.python.PythonPlannerRunner.runInPython(PythonPlannerRunner.scala:120)
  at org.apache.spark.sql.execution.datasources.v2.python.UserDefinedPythonDataSource.createWriteInfoInPython(UserDefinedPythonDataSource.scala:94)
  at org.apache.spark.sql.execution.datasources.v2.python.PythonBatchWrite.createBatchWriterFactory(PythonWrite.scala:67)
  at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.writeWithV2(WriteToDataSourceV2Exec.scala:408)
  at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.writeWithV2$(WriteToDataSourceV2Exec.scala:394)
  at org.apache.spark.sql.execution.datasources.v2.AppendDataExec.writeWithV2(WriteToDataSourceV2Exec.scala:237)
  at org.apache.spark.sql.execution.datasources.v2.V2ExistingTableWriteExec.run(WriteToDataSourceV2Exec.scala:359)
  ...
22:46:15.562 WARN org.apache.spark.sql.execution.python.PythonDataSourceSuite:

Run completed in 16 seconds, 889 milliseconds.
Total number of tests run: 22
Suites: completed 2, aborted 0
Tests: succeeded 17, failed 5, canceled 0, ignored 0, pending 0
*** 5 TESTS FAILED ***
```

after

```
Run completed in 20 seconds, 600 milliseconds.
Total number of tests run: 22
Suites: completed 2, aborted 0
Tests: succeeded 22, failed 0, canceled 0, ignored 0, pending 0
All tests passed.
```

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #50320 from LuciferYang/default-OBJC_DISABLE_INITIALIZE_FORK_SAFETY.

Authored-by: yangjie01 <yangjie01@baidu.com>
Signed-off-by: yangjie01 <yangjie01@baidu.com>