[MINOR][TESTS] Restore classic-only python tests
### What changes were proposed in this pull request?
Restore classic-only python tests

### Why are the changes needed?
https://github.com/apache/spark/actions/runs/17750573817/job/50444653160

it is failing with
```
Starting test(python3.11): pyspark.sql.tests.connect.client.test_client (temp output: /__w/spark/spark/python/target/8bab95ed-f5f1-47cb-9564-5c7d71b4239e/python3.11__pyspark.sql.tests.connect.client.test_client__h0939y47.log)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/__w/spark/spark/python/pyspark/sql/tests/connect/client/test_client.py", line 23, in <module>
    from pyspark.errors.exceptions.connect import SparkConnectGrpcException
  File "/__w/spark/spark/python/pyspark/errors/exceptions/connect.py", line 17, in <module>
    import grpc
ModuleNotFoundError: No module named 'grpc'

```

### Does this PR introduce _any_ user-facing change?
no, test-only

### How was this patch tested?
will monitor the scheduled jobs

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #52379 from zhengruifeng/restore_classic_test.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>