[SPARK-47095][INFRA] Uses proper options for command script in macos-14 build
### What changes were proposed in this pull request?

This PR fixes `maven_test.yml` compatible with macos-14 by fixing `script` command options.

### Why are the changes needed?

https://github.com/apache/spark/actions/runs/7964626045/job/21742573399

It fails as below:

```
Run # Fix for TTY related issues when launching the Ammonite REPL in tests.
/usr/bin/script: illegal option -- c
usage: script [-aeFkpqr] [-t time] [file [command ...]]
       script -p [-deq] [-T fmt] [file]
Error: Process completed with exit code 1.
```

See https://man.freebsd.org/cgi/man.cgi?script(1)
https://man7.org/linux/man-pages/man1/script.1.html

### Does this PR introduce _any_ user-facing change?

No, test-only.

### How was this patch tested?

Manually tested in my local.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #45171 from HyukjinKwon/SPARK-47095.

Authored-by: Hyukjin Kwon <gurwls223@apache.org>
Signed-off-by: Dongjoon Hyun <dhyun@apple.com>