[SPARK-52592][PS] Support creating a ps.Series from a ps.Series
### What changes were proposed in this pull request?

I fixed the constructor to explicitly handle `Series` input similar to how it handles `DataFrame` input. It previously would fall to the else case that inputs it into a regular pandas Series constructor, leading to the error.

### Why are the changes needed?

Previously, this code
```
obj = ps.Series([x for x in range(3)])
obj = ps.Series(obj)
```
would error:
```
...
pyspark.pandas.exceptions.PandasNotImplementedError: The method `pd.Series.__iter__()` is not implemented. If you want to collect your data as an NumPy array, use 'to_numpy()' instead.
```

### Does this PR introduce _any_ user-facing change?

Yes, previously, when you try to pass a `ps.Series` object into the `ps.Series.__init__()`, you can an error. Now, it will work successfully similar to how traditional pandas Series works.

### How was this patch tested?

Yes, I added a test.

### Was this patch authored or co-authored using generative AI tooling?

No

Closes #51300 from petern48/series_from_series.

Authored-by: Peter Nguyen <petern0408@gmail.com>
Signed-off-by: Takuya Ueshin <ueshin@databricks.com>