[SPARK-51603][CONNECT][TESTS] Auto ignore tests that require starting `SparkConnectServer` when the directory `assembly/target/scala-2.13/jars/` not exist
### What changes were proposed in this pull request?
After the merge of SPARK-48936 (https://github.com/apache/spark/pull/47402), the Maven module compilation order for the `connect-client-jvm` module was moved up to occur before the `assembly` build.

Since a portion of the tests in `connect-client-jvm` heavily rely on `SparkConnectServer` and related dependencies being collected into `assembly/target/scala-2.13/jars/`, it is necessary to build `assembly` before running `mvn test` for `connect-client-jvm`.

For example:

```
build/mvn clean install -DskipTests -Phive
build/mvn test -pl sql/connect/client/jvm
```

This sequence will result in successful tests.

However, if a full test suite is executed directly, such as:

```
build/mvn clean install -Phive
```

Failures similar to the following may occur:

```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.044 s <<< FAILURE! -- in org.apache.spark.sql.JavaEncoderSuite
[ERROR] org.apache.spark.sql.JavaEncoderSuite -- Time elapsed: 0.044 s <<< FAILURE!
java.lang.AssertionError: assertion failed: Fail to locate the target folder: '/Users/yangjie01/SourceCode/git/spark-maven/sql/connect/server/target'. SPARK_HOME='/Users/yangjie01/SourceCode/git/spark-maven'. Make sure the spark project jars has been built (e.g. using build/sbt package)and the env variable `SPARK_HOME` is set correctly.
  at scala.Predef$.assert(Predef.scala:279)
  at org.apache.spark.sql.connect.test.IntegrationTestUtils$.tryFindJar(IntegrationTestUtils.scala:138)
  at org.apache.spark.sql.connect.test.IntegrationTestUtils$.findJar(IntegrationTestUtils.scala:116)
  at org.apache.spark.sql.connect.test.SparkConnectServerUtils$.sparkConnect$lzycompute(RemoteSparkSession.scala:65)
  at org.apache.spark.sql.connect.test.SparkConnectServerUtils$.sparkConnect(RemoteSparkSession.scala:62)
  at org.apache.spark.sql.connect.test.SparkConnectServerUtils$.start(RemoteSparkSession.scala:135)
  at org.apache.spark.sql.connect.test.SparkConnectServerUtils$.createSparkSession(RemoteSparkSession.scala:181)
  at org.apache.spark.sql.connect.test.SparkConnectServerUtils.createSparkSession(RemoteSparkSession.scala)
  at org.apache.spark.sql.JavaEncoderSuite.setup(JavaEncoderSuite.java:42)
  at java.base/java.lang.reflect.Method.invoke(Method.java:569)
  at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  Suppressed: java.lang.NullPointerException: Cannot invoke "org.apache.spark.sql.SparkSession.stop()" because "org.apache.spark.sql.JavaEncoderSuite.spark" is null
    at org.apache.spark.sql.JavaEncoderSuite.tearDown(JavaEncoderSuite.java:47)
    at java.base/java.lang.reflect.Method.invoke(Method.java:569)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
    at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
    ... 1 more

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   JavaEncoderSuite.setup:42 assertion failed: Fail to locate the target folder: '/Users/yangjie01/SourceCode/git/spark-maven/sql/connect/server/target'. SPARK_HOME='/Users/yangjie01/SourceCode/git/spark-maven'. Make sure the spark project jars has been built (e.g. using build/sbt package)and the env variable `SPARK_HOME` is set correctly.
[INFO]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

To ensure that the above failing scenario can be tested successfully, the current pr makes the following changes:

1. Added `isAssemblyJarsDirExists` in `IntegrationTestUtils` to check if the directory `assembly/target/scala-2.13/jars/` exists.
2. Overrode the `test` function in the `trait RemoteSparkSession` from `AnyFunSuite` to ignore corresponding tests when `isAssemblyJarsDirExists` is `false`. Additionally, `RemoteSparkSession` will only try to start `SparkConnectServer` when `isAssemblyJarsDirExists` is `true`.
3. Made similar changes in `JavaEncoderSuite` as in step 2

### Why are the changes needed?
Make the Maven testing process smoother.

### Does this PR introduce _any_ user-facing change?
No, just for maven test.

### How was this patch tested?
- Pass Git Hub Actions
- Tested the  `connect-client-jvm` module using Maven without `assembly` dir , and the results met expectations.

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #50396 from LuciferYang/SPARK-51603.

Lead-authored-by: yangjie01 <yangjie01@baidu.com>
Co-authored-by: YangJie <yangjie01@baidu.com>
Signed-off-by: yangjie01 <yangjie01@baidu.com>
(cherry picked from commit 998242732927907ddae3cfaf4f64220ae79552e3)
Signed-off-by: yangjie01 <yangjie01@baidu.com>