[SPARK-46146][INFRA] Unpin `markupsafe`
### What changes were proposed in this pull request?
Unpin `markupsafe`

### Why are the changes needed?
latest version no longer causes `"ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.9/dist-packages/markupsafe/{}init{}.py)"` mentioned in https://issues.apache.org/jira/browse/SPARK-38279

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
ci

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #44062 from zhengruifeng/infra_unpin_MarkupSafe.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>