[SPARK-38155][SQL] Disallow distinct aggregate in lateral subqueries with unsupported predicates
### What changes were proposed in this pull request?
This PR blocks lateral subqueries that contain DISTINCT aggregate and correlated non-equality predicates in CheckAnalysis.

### Why are the changes needed?
To avoid incorrect results. `DISTINCT` will be rewritten into Aggregate during the optimization phase and only correlated equality predicates are supported with Aggregate.

Note, we only need to block this pattern for lateral subqueries because 1) Scalar subqueries are either aggregated or can only contain one row, so they will not encounter this issue 2) IN/EXISTS subqueries can potentially have the same issue but it won't impact the results of these subqueries, for example, `SELECT * FROM t1 WHERE c1 IN (SELECT DISTINCT c1 FROM t2 WHERE t1.c1 > t2.c1)`.

### Does this PR introduce _any_ user-facing change?
Yes. Queries with lateral joins that contain DISTINCT aggregate will be blocked:
```
SELECT * FROM t1 JOIN LATERAL (SELECT DISTINCT c2 FROM t2 WHERE c1 > t1.c1)

AnalysisException: Correlated column is not allowed in predicate
```

### How was this patch tested?
Unit tests.

Closes #35469 from allisonwang-db/spark-38155-distinct.

Authored-by: allisonwang-db <allison.wang@databricks.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>