[SPARK-42171][PYSPARK][TESTS] Fix `pyspark-errors` module and enable it in GitHub Action
### What changes were proposed in this pull request?

This PR aims to enable `pyspark-errors` module test coverall in GitHub Action and fix it.

### Why are the changes needed?

#39387 added `pyspark_errors` module, but didn't enable it in GitHub Action.

The bug was not exposed in #39387 initially because `ERROR_CLASSES_JSON` has only one item in this PR.

https://github.com/apache/spark/blob/ae6cc8f5b52d74a8ff8aac955461c1506f24a5c9/python/pyspark/errors/tests/test_errors.py#L31

The bug is exposed in the subsequent PRs. So, currently, it's broken.

```
$ python/run-tests.py --modules pyspark-errors
...
test_error_classes (pyspark.errors.tests.test_errors.ErrorsTest.test_error_classes) ... ERROR

======================================================================
ERROR: test_error_classes (pyspark.errors.tests.test_errors.ErrorsTest.test_error_classes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dongjoon/APACHE/spark-merge/python/pyspark/errors/tests/test_errors.py", line 31, in test_error_classes
    error_class_names[i] < error_class_names[i + 1],
    ~~~~~~~~~~~~~~~~~^^^
KeyError: 0
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

This PR shows the failure at the first commit by adding `pyspark-errors` test coverage.
- https://github.com/dongjoon-hyun/spark/actions/runs/3999180114/jobs/6862791939

The second commit passed `pyspark-errors` in the CIs.
- https://github.com/dongjoon-hyun/spark/actions/runs/3999260298/jobs/6862968301

Closes #39721 from dongjoon-hyun/SPARK-42171.

Authored-by: Dongjoon Hyun <dongjoon@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>