[MINOR][TEST] Add output/exception to error message when schema not matched in `TPCDSQueryTestSuite`
### What changes were proposed in this pull request?

This patch adds output/exception string to the error message when output schema not match expected schema in `TPCDSQueryTestSuite`.

### Why are the changes needed?

We have used `TPCDSQueryTestSuite` for testing TPCDS query results. The test suite checks output schema and then output result. If any exception happens during query execution, it will handle the exception and return an empty schema and exception class + message as output. So, when any exception happens, the test suite just fails on schema check and never uses/shows the exception, e.g.,

```
java.lang.Exception: Expected "struct<[count(1):bigint]>", but got "struct<[]>" Schema did not match
```

We cannot see what exception was happened there from the log. It is somehow inconvenient for debugging.

### Does this PR introduce _any_ user-facing change?

No, test only.

### How was this patch tested?

Existing tests

### Was this patch authored or co-authored using generative AI tooling?

No

Closes #45025 from viirya/minor_ouput_exception.

Authored-by: Liang-Chi Hsieh <viirya@gmail.com>
Signed-off-by: Dongjoon Hyun <dhyun@apple.com>