[SPARK-38966][CI] Allow fork branches to be in-sync with upstream master
### What changes were proposed in this pull request?
Make `git commit` in `.github/workflows/build_and_test.yml` work with empty commits by adding `--allow-empty` to the command.

### Why are the changes needed?
Whenever I sync my fork master from upstream Apache master, CI fails:

```
From https://github.com/G-Research/spark
 * branch                  master     -> FETCH_HEAD
Already up to date. (nothing to squash)
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
Error: Process completed with exit code 1.
```

Since my fork master is without changes, the `git commit` fails. This is annoying.

The same issue makes the scheduled build and test workflow fail multiple times a day.

### Does this PR introduce _any_ user-facing change?
No, this is CI only.

### How was this patch tested?
Tested `git commit --allow-empty` with no changes on command line.

Closes #36263 from EnricoMi/branch-allow-for-synced-fork-branches.

Authored-by: Enrico Minack <github@enrico.minack.dev>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>