[SPARK-53688][PYTHON][INFRA][TESTS] Increase the timeout and skip UDF type tests in Python-only on MacOS
### What changes were proposed in this pull request?
Restore scheduled job Python on MacOS

### Why are the changes needed?
there are several issues in `Build / Python-only (master, Python 3.11, MacOS)`:
1, timeout (see https://github.com/apache/spark/actions/runs/17959033758/job/51077768376)
due to
```
Starting test(python3.11): pyspark.sql.tests.pandas.test_pandas_transform_with_state (temp output: /Users/runner/work/spark/spark/python/target/e6f2d46f-d9dd-48ac-8a90-d6e23b1fa732/python3.11__pyspark.sql.tests.pandas.test_pandas_transform_with_state__w2vr990g.log)
Finished test(python3.11): pyspark.sql.tests.pandas.test_pandas_transform_with_state (2627s) ... 4 tests were skipped
```
and
```
Starting test(python3.11): pyspark.sql.tests.connect.pandas.test_parity_pandas_transform_with_state (temp output: /Users/runner/work/spark/spark/python/target/cb180fcf-43fa-4399-af2c-cb4fbce43cc5/python3.11__pyspark.sql.tests.connect.pandas.test_parity_pandas_transform_with_state___59n8od_.log)
Finished test(python3.11): pyspark.sql.tests.connect.pandas.test_parity_pandas_transform_with_state (1353s) ... 4 tests were skipped
```

2, test failure of newly added UDF input/output type check
```
======================================================================
ERROR [0.004s]: test_assert_classic_mode (__main__.UDFReturnTypeTests.test_assert_classic_mode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/spark/spark/python/pyspark/sql/tests/udf_type_tests/test_udf_return_types.py", line 107, in setUp
    np.arange(1, 3).astype("float128"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: data type 'float128' not understood
```
based on my investigation, `np.float128` is platform specific, and seems not supported on macos;

3, flaky ml tests, which failed occasionally

this PR attempt to resolve 1) and 2)

### Does this PR introduce _any_ user-facing change?
no, test-only

### How was this patch tested?
will monitor the CI

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #52429 from zhengruifeng/skip_udf_inout_macos.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>