[SPARK-45681][UI][FOLLOWUP] Check maybeErrorClass instead of maybeErrorClass.length
### What changes were proposed in this pull request?

The `String.match` function may return null if no matches are found. This reverts the suggestion from https://github.com/apache/spark/pull/43547#discussion_r1375487690 to avoid `TypeError: Cannot read properties of null (reading 'length')`

### Why are the changes needed?

bugfix

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

An UPCOMING javascript test framework for Spark UI

```javascript
FAIL  tests/utils.test.js
  ✓ formatDuration (2 ms)
  ✓ formatBytes
  ✓ formatTimeMillis (1 ms)
  ✕ errorSummary (1 ms)

  ● errorSummary

    TypeError: Cannot read properties of null (reading 'length')

      254 |   const maybeErrorClass = errorMessage.match(ERROR_CLASS_REGEX);
      255 |   let errorClassOrBrief;
    > 256 |   if (maybeErrorClass.length === 2) {
          |                       ^
      257 |     errorClassOrBrief = maybeErrorClass[1];
      258 |   } else if (errorMessage.indexOf('\n') >= 0) {
      259 |     errorClassOrBrief = errorMessage.substring(0, errorMessage.indexOf('\n'));

      at length (utils.js:256:23)
      at Object.errorSummary (tests/utils.test.js:58:10)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 3 passed, 4 total
Snapshots:   0 total
Time:        0.149 s, estimated 1 s
```

```javascript
 PASS  tests/utils.test.js
  ✓ formatDuration (1 ms)
  ✓ formatBytes (1 ms)
  ✓ formatTimeMillis (1 ms)
  ✓ errorSummary

Test Suites: 1 passed, 1 total
Tests:       4 passed, 4 total
Snapshots:   0 total
```

### Was this patch authored or co-authored using generative AI tooling?

no

Closes #43872 from yaooqinn/SPARK-45681-F.

Authored-by: Kent Yao <yao@apache.org>
Signed-off-by: Dongjoon Hyun <dhyun@apple.com>