[SPARK-39517][INFRA] Recover branch-3.2 build broken by is-changed.py script missing
### What changes were proposed in this pull request?

Currently scheduled jobs fail as below (https://github.com/apache/spark/runs/6913767185?check_suite_focus=true):

```
Run build=`./dev/is-changed.py -m avro,build,catalyst,core,docker-integration-tests,examples,graphx,hadoop-cloud,hive,hive-thriftserver,kubernetes,kvstore,launcher,mesos,mllib,mllib-local,network-common,network-shuffle,pyspark-core,pyspark-ml,pyspark-mllib,pyspark-pandas,pyspark-pandas-slow,pyspark-resource,pyspark-sql,pyspark-streaming,repl,sketch,spark-ganglia-lgpl,sparkr,sql,sql-kafka-0-10,streaming,streaming-kafka-0-10,streaming-kinesis-asl,tags,unsafe,yarn`
/home/runner/work/_temp/f86503c6-6b49-448e-b4b7-ac31411a87db.sh: line 1: ./dev/is-changed.py: No such file or directory
Error: Process completed with exit code 127.
```

because `is-changed.py` script is missing. The scheduled jobs are created by `master` branch. This PR fixes it by explicitly setting all modules to test if the script is missing.

### Why are the changes needed?

To recover the scheduled builds in branch-3.2.

### Does this PR introduce _any_ user-facing change?

No, test-only.

### How was this patch tested?

I manually tested the fixed shell commands locally.

Closes #36915 from HyukjinKwon/SPARK-39517.

Authored-by: Hyukjin Kwon <gurwls223@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>