[DOCS][MINOR] Remove spark-sql-api dependency from connect docs
### What changes were proposed in this pull request?
Remove `spark-sql-api` dependency from documentation.

### Why are the changes needed?
Dependency `spark-connect-client-jvm` is sufficient, as it includes (shaded) the `spark-sql-api` package.

In fact, adding the `spark-sql-api` dependency breaks runtime:
1. transient dependency `io.netty:netty-buffer`, that is also included in `spark-connect-client-jvm` (shaded) cannot be found: `NoClassDefFoundError: io/netty/buffer/PooledByteBufAllocator`
2. method `ArrowUtils$.toArrowSchema` provided by `spark-sql-api` cannot be found: `NoSuchMethodError: 'org.sparkproject.org.apache.arrow.vector.types.pojo.Schema org.apache.spark.sql.util.ArrowUtils$.toArrowSchema(org.apache.spark.sql.types.StructType, java.lang.String, boolean, boolean)'`

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Manually with minimal maven project.

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #48119 from EnricoMi/docs-connect-jvm-deps.

Authored-by: Enrico Minack <github@enrico.minack.dev>
Signed-off-by: Herman van Hovell <herman@databricks.com>