[SPARK-51822][SS] Throwing classified error when disallowed functions are called during StatefulProcessor.init()
### What changes were proposed in this pull request?

When state variable operations are called within the init() function of the StatefulProcessorHandle, a NullPointerException is thrown, failing the query (even through this is user error).
Throw an error with a message that better describes the issue.

### Why are the changes needed?

The NullPointerException doesn't describe the issue to the user, even though this is user error. This will let them know that the function they are calling within `init()` is disallowed.

### Does this PR introduce _any_ user-facing change?

Before this change:
```
12:20:32.646 ERROR org.apache.spark.sql.execution.streaming.MicroBatchExecution: Query [id = 9a666389-5fc4-4c4c-b621-5730f9e9bd03, runId = d3535902-1c7a-442a-b52c-701d2511e56c] terminated with error
org.apache.spark.SparkException: [INTERNAL_ERROR] The Spark SQL phase planning failed with an internal error. You hit a bug in Spark or the Spark plugins you use. Please, report this bug to the corresponding communities or vendors, and provide the full stack trace. SQLSTATE: XX000
	at org.apache.spark.SparkException$.internalError(SparkException.scala:107)
	at org.apache.spark.sql.execution.QueryExecution$.toInternalError(QueryExecution.scala:631)
```

After this change:

```
11:52:20.303 ERROR org.apache.spark.sql.execution.streaming.MicroBatchExecution: Query [id = 81b2e2ff-ca37-4d40-a533-2848de6984b5, runId = 29bbdc65-f198-440f-b2ba-20700159f839] terminated with error
org.apache.spark.sql.execution.streaming.state.StatefulProcessorCannotPerformOperationWithInvalidHandleState: [STATEFUL_PROCESSOR_CANNOT_PERFORM_OPERATION_WITH_INVALID_HANDLE_STATE] Failed to perform stateful processor operation=listState.exists with invalid handle state=PRE_INIT. SQLSTATE: 42802
	at org.apache.spark.sql.execution.streaming.state.StateStoreErrors$.cannotPerformOperationWithInvalidHandleState(StateStoreErrors.scala:123)
```

### How was this patch tested?

Unit tests

### Was this patch authored or co-authored using generative AI tooling?

No

Closes #50611 from ericm-db/tws-error-classification.

Authored-by: Eric Marnadi <eric.marnadi@databricks.com>
Signed-off-by: Jungtaek Lim <kabhwan.opensource@gmail.com>