[SPARK-46397][PYTHON][CONNECT] Function `sha2` should raise `PySparkValueError` for invalid `numBits`
### What changes were proposed in this pull request?
Function `sha2`  should raise `PySparkValueError` for invalid `numBits`

### Why are the changes needed?
vanilla PySpark invokes the Scala side and raise an `IllegalArgumentException`
https://github.com/apache/spark/blob/7a2920f332b1c5ad8f518f4d13f7ab97426f5811/sql/core/src/main/scala/org/apache/spark/sql/functions.scala#L3212-L3217

while Python client won't do this check and raise an `AnalysisException`.

They should both raise a `PySparkValueError` for this case.

### Does this PR introduce _any_ user-facing change?
yes

```
In [1]: from pyspark.sql import functions as sf
   ...: spark.range(1).select(sf.sha2(sf.col("id"), 1024)).collect()
---------------------------------------------------------------------------
PySparkValueError                         Traceback (most recent call last)
<ipython-input-1-1ae9879dcc31> in ?()
      1 from pyspark.sql import functions as sf
----> 2 spark.range(1).select(sf.sha2(sf.col("id"), 1024)).collect()

~/Dev/spark/python/pyspark/sql/utils.py in ?(*args, **kwargs)
    190             from pyspark.sql.connect import functions
    191
    192             return getattr(functions, f.__name__)(*args, **kwargs)
    193         else:
--> 194             return f(*args, **kwargs)

~/Dev/spark/python/pyspark/sql/functions/builtin.py in ?(col, numBits)
   9112     |Bob  |cd9fb1e148ccd8442e5aa74904cc73bf6fb54d1d54d333bd596aa9bb4bb4e961|
   9113     +-----+----------------------------------------------------------------+
   9114     """
   9115     if numBits not in [0, 224, 256, 384, 512]:
-> 9116         raise PySparkValueError(
   9117             error_class="VALUE_NOT_ALLOWED",
   9118             message_parameters={
   9119                 "arg_name": "numBits",

PySparkValueError: [VALUE_NOT_ALLOWED] Value for `numBits` has to be amongst the following values: [0, 224, 256, 384, 512].
```

### How was this patch tested?
added ut

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #44529 from zhengruifeng/py_connect_sha2_check.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>