[SPARK-53300][PYTHON][TESTS] Fix field names in test_unpivot
### What changes were proposed in this pull request?
Fix field names in test_unpivot

### Why are the changes needed?
the field names in the test are incorrect, (although comparing rows seems ignores the names)

```
======================================================================
FAIL [0.000s]: test_unpivot (pyspark.sql.tests.connect.test_parity_stat.DataFrameStatParityTests.test_unpivot) (ids=[], desc='with no identifier')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/python/pyspark/sql/tests/test_stat.py", line 435, in test_unpivot
    self.assertEqual(
AssertionError: Lists differ: [Row(var='int', val=10.0), Row(var='int', val=20.0), Row(var[97 chars]3.0)] != [Row(var='int', value=10.0), Row(var='double', value=1.0), R[109 chars]3.0)]
First differing element 1:
Row(var='int', val=20.0)
Row(var='double', value=1.0)
- [Row(var='int', val=10.0),
+ [Row(var='int', value=10.0),
?                    ++
-  Row(var='int', val=20.0),
-  Row(var='int', val=30.0),
-  Row(var='double', val=1.0),
+  Row(var='double', value=1.0),
?                       ++
+  Row(var='int', value=20.0),
-  Row(var='double', val=2.0),
+  Row(var='double', value=2.0),
?                       ++
+  Row(var='int', value=30.0),
-  Row(var='double', val=3.0)]
+  Row(var='double', value=3.0)]
?                       ++
```

### Does this PR introduce _any_ user-facing change?
test-only

### How was this patch tested?
ci

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #52053 from zhengruifeng/fix_test_parity_stat.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>