[SPARK-37903][PYTHON][FOLLOW-UP] Raise ValueError with no return function
### What changes were proposed in this pull request?
Raise ValueError with no return function

### Why are the changes needed?
This PR is a follow-up of https://github.com/apache/spark/pull/35200
Currently, with the function with no return, `infer_return_type` will return `ScalarType[DoubleType]` as default. We should raise exception for this case.

### Does this PR introduce _any_ user-facing change?
Yes,
Before this PR
```python
>>> from pyspark.pandas.typedef.typehints import infer_return_type
>>> def f():
...     pass
...
>>> infer_return_type(f)
ScalarType[DoubleType]
```

after this PR user will take an exception when infer return type of function with no return.
```python-traceback
>>> from pyspark.pandas.typedef.typehints import infer_return_type
>>> def f():
...     pass
...
>>> infer_return_type(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u02/spark/python/pyspark/pandas/typedef/typehints.py", line 563, in infer_return_type
    raise ValueError("A return value is required for the input function")
ValueError: A return value is required for the input function

```

### How was this patch tested?
unit test

Closes #35236 from dchvn/SPARK-37903-FU.

Authored-by: dch nguyen <dchvn.dgd@gmail.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>