[SPARK-40598][PS] Fix plotting features work properly with pandas 1.5.0
### What changes were proposed in this pull request?

This PR proposes to fix the plotting functions working properly with pandas 1.5.0.

This includes two fixes:
- Fix the `PandasOnSpark*Plot` to get name of plot in the string format properly.
- Fix the default value of `subplots` parameter from `plot_frame` to match with latest pandas. (`None` -> `False`)

### Why are the changes needed?

#### 1. get `_kind` from pandas class no longer possible.

We're leverage the pandas plotting classes to implement for `matplotlib` implementation, and get the class name from pandas like:
```python
>>> from pandas.plotting._matplotlib.core import AreaPlot
>>> AreaPlot._kind
'area'
```
However, since pandas 1.5.0, they convert the member variable `_kind` into `property`, so we cannot bring the name of class properly from pandas class as below:
```python
>>> from pandas.plotting._matplotlib.core import AreaPlot
AreaPlot._kind
>>> AreaPlot._kind
<property object at 0x7fe520d749a0>
```

#### 2. `subplots` parameter no longer allow the type other than `Iterable` or `bool`.

We internally set the default value for `subplots` as `None`, but from pandas 1.5.0 only allows `Iterable` or `bool`, so the plotting function is not work properly as below:

```python
>>> psdf.plot(kind="bar")
Traceback (most recent call last):
...
ValueError: subplots should be a bool or an iterable
```

With this fixes, it work properly with pandas 1.5.0 as below:

**<For Series and DataFrame plot>**

**Before**:
```python
>>> from pyspark.pandas.config import set_option
>>> set_option("plotting.backend", "matplotlib")
>>> import pyspark.pandas as ps
>>> psdf = ps.range(10)
>>> psdf.plot(kind="bar")
Traceback (most recent call last):
...
KeyError: 'bar'
```

**After**:
```python
>>> from pyspark.pandas.config import set_option
>>> set_option("plotting.backend", "matplotlib")
>>> import pyspark.pandas as ps
>>> psdf = ps.range(10)
>>> psdf.plot(kind="bar")
<AxesSubplot:>
```

**<For DataFrame plot>**

**Before**:
```python
>>> from pyspark.pandas.config import set_option
>>> set_option("plotting.backend", "matplotlib")
>>> import pyspark.pandas as ps
>>> psdf = ps.range(10)
>>> psdf.plot(kind="bar")
Traceback (most recent call last):
...
ValueError: subplots should be a bool or an iterable
```

**After**:
```python
>>> from pyspark.pandas.config import set_option
>>> set_option("plotting.backend", "matplotlib")
>>> import pyspark.pandas as ps
>>> psdf = ps.range(10)
>>> psdf.plot(kind="bar")
<AxesSubplot:>
```

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Manually tested with pandas 1.5.0.

Closes #38033 from itholic/fix_plot_test.

Authored-by: itholic <haejoon.lee@databricks.com>
Signed-off-by: Xinrong Meng <xinrong@apache.org>