[SPARK-37721][PYTHON] Fix SPARK_HOME key error when running PySpark test
### What changes were proposed in this pull request?
Replace `os.environ["SPARK_HOME"]` direct access with `_find_spark_home` in pyspark testing utils.

### Why are the changes needed?
When running PySpark unit test in WSL with PyCharm, all test raise the `KeyError: 'SPARK_HOME'`
```
Launching unittests with arguments python -m unittest test_rdd.RDDTests.test_range in /home/yikun/spark/python/pyspark/testsTraceback (most recent call last):
  File "/mnt/d/Program Files/JetBrains/PyCharm 2021.1.3/plugins/python/helpers/pycharm/_jb_unittest_runner.py", line 35, in <module>
    sys.exit(main(argv=args, module=None, testRunner=unittestpy.TeamcityTestRunner, buffer=not JB_DISABLE_BUFFERING))
  File "/usr/lib/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.8/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/usr/lib/python3.8/unittest/main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "/usr/lib/python3.8/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.8/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/yikun/spark/python/pyspark/tests/test_rdd.py", line 37, in <module>
    from pyspark.testing.utils import ReusedPySparkTestCase, SPARK_HOME, QuietTest
  File "/home/yikun/spark/python/pyspark/testing/utils.py", line 47, in <module>
    SPARK_HOME = os.environ["SPARK_HOME"]#_find_spark_home()
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'SPARK_HOME'
```

We should use `_find_spark_home` to get SPARK_HOME rather than access `os.environ`.

### Does this PR introduce _any_ user-facing change?
No, test only

### How was this patch tested?
- UT passed.
- Run test in Win WSL.

Closes #34993 from Yikun/SPARK-WSL-TEST.

Authored-by: Yikun Jiang <yikunkero@gmail.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>