[SPARK-49188][SQL] Internal error on concat_ws called on array of arrays of string
### What changes were proposed in this pull request?

Applying the following sequence of queries in **ANSI mode** (`spark.sql.ansi.enabled=true`):
```
create table test_table(dat array<string>) using parquet;
select concat_ws(',', collect_list(dat)) FROM test_table;
```
yields an internal error:
```
org.apache.spark.SparkException: [INTERNAL_ERROR] The Spark SQL phase analysis failed with an internal error. You hit a bug in Spark or the Spark plugins you use. Please, report this bug to the corresponding communities or vendors, and provide the full stack trace. SQLSTATE: XX000
...
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.spark.sql.types.AbstractDataType.simpleString()" because "<local3>" is null
  at org.apache.spark.sql.errors.DataTypeErrorsBase.toSQLType(DataTypeErrorsBase.scala:55)
  at org.apache.spark.sql.errors.DataTypeErrorsBase.toSQLType$(DataTypeErrorsBase.scala:51)
  at org.apache.spark.sql.catalyst.expressions.Cast$.toSQLType(Cast.scala:44)
  at org.apache.spark.sql.catalyst.expressions.Cast$.typeCheckFailureMessage(Cast.scala:426)
  at org.apache.spark.sql.catalyst.expressions.Cast.typeCheckFailureInCast(Cast.scala:501)
  at org.apache.spark.sql.catalyst.expressions.Cast.checkInputDataTypes(Cast.scala:525)
  at org.apache.spark.sql.catalyst.expressions.Cast.resolved$lzycompute(Cast.scala:551)
  at org.apache.spark.sql.catalyst.expressions.Cast.resolved(Cast.scala:550)
...
```
Fix the problematic pattern-matching rule in `AnsiTypeCoercion`.

### Why are the changes needed?

Replace the internal error with proper user-facing error.

### Does this PR introduce _any_ user-facing change?

Yes, it removes the internal error user could produce by running queries.

### How was this patch tested?

Added tests to `AnsiTypeCoercionSuite` and `StringFunctionsSuite`.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #47691 from nikolamand-db/SPARK-49188.

Authored-by: Nikola Mandic <nikola.mandic@databricks.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>