[SPARK-42733][CONNECT][PYTHON] Fix DataFrameWriter.save to work without path parameter
### What changes were proposed in this pull request?

Fixes `DataFrameWriter.save` to work without path parameter.

### Why are the changes needed?

`DataFrameWriter.save` should work without path parameter because some data sources, such as jdbc, noop, works without those parameters.

```py
>>> print(spark.range(10).write.format("noop").mode("append").save())
Traceback (most recent call last):
...
AssertionError: Invalid configuration of WriteCommand, neither path or table present.
```

### Does this PR introduce _any_ user-facing change?

The data sources that don't need path parameter will work.

```py
>>> print(spark.range(10).write.format("noop").mode("append").save())
None
```

### How was this patch tested?

Added a test.

Closes #40356 from ueshin/issues/SPARK-42733/save.

Authored-by: Takuya UESHIN <ueshin@databricks.com>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>