[SPARK-53301][PYTHON] Differentiate type hints of Pandas UDF and Arrow UDF
### What changes were proposed in this pull request?
Differentiate type hints of Pandas UDF and Arrow UDF

### Why are the changes needed?
The `arrow_udf` can works with a pandas udf, and the `pandas_udf` can works with a arrow udf, because the eval type inference didn't differentiate the pandas udf and arrow udf.
But this is supposed to fail.

before:
```
In [1]: import pyarrow as pa
   ...:
   ...: from pyspark.sql import functions as sf
   ...: from pyspark.sql.functions import arrow_udf, pandas_udf
   ...:
   ...: df = spark.range(10).withColumn("v", sf.col("id") + 1)
   ...:
   ...:
   ...: pandas_udf("long")
   ...: def multiply_arrow_func(a: pa.Array, b: pa.Array) -> pa.Array:
   ...:     assert isinstance(a, pa.Array)
   ...:     assert isinstance(b, pa.Array)
   ...:     return pa.compute.multiply(a, b)
   ...:
   ...:

In [2]: df.select("id", "v", multiply_arrow_func("id", "v").alias("m")).show()
   ...:
+---+---+---+
| id|  v|  m|
+---+---+---+
|  0|  1|  0|
|  1|  2|  2|
|  2|  3|  6|
|  3|  4| 12|
|  4|  5| 20|
|  5|  6| 30|
|  6|  7| 42|
|  7|  8| 56|
|  8|  9| 72|
|  9| 10| 90|
+---+---+---+
```

after
```
In [2]:    ...: pandas_udf("long")
   ...:    ...: def multiply_arrow_func(a: pa.Array, b: pa.Array) -> pa.Array:
   ...:    ...:     assert isinstance(a, pa.Array)
   ...:    ...:     assert isinstance(b, pa.Array)
   ...:    ...:     return pa.compute.multiply(a, b)
   ...:
---------------------------------------------------------------------------
PySparkNotImplementedError                Traceback (most recent call last)

...

PySparkNotImplementedError: [UNSUPPORTED_SIGNATURE] Unsupported signature: (a: pyarrow.lib.Array, b: pyarrow.lib.Array) -> pyarrow.lib.Array.

```

### Does this PR introduce _any_ user-facing change?
no, arrow_udf is not yet released

### How was this patch tested?
new tests

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #52054 from zhengruifeng/arrow_pandas_type_hint.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>