[SPARK-37657][PYTHON] Support str and timestamp for (Series|DataFrame).describe()
### What changes were proposed in this pull request?

This PR proposes to support string and timestamp type columns for `(Series|DataFrame).describe()` API.

Now `(Series|DataFrame).describe()` API only supports the numeric type column, so we should support other types.

The initial issue is reported from Koalas user in legacy Koalas repo (https://github.com/databricks/koalas/issues/1888).

### Why are the changes needed?

We should match the latest pandas' behavior as much as possible.

### Does this PR introduce _any_ user-facing change?

Users can apply the `(Series|DataFrame).describe()` API to the string and timestamp type columns which is unavailable before this fix.

**Before**
```python
>>> df = ps.DataFrame({'a': ["a", "b", "c"]})
>>> df.describe()
Traceback (most recent call last):
...
ValueError: Cannot describe a DataFrame without columns
```

**After**
```python
>>> df = ps.DataFrame({'a': ["a", "b", "c"]})
>>> df.describe()
        a
count   3
unique  3
top     a
freq    1
```

### How was this patch tested?

Added unittests.

Closes #34931 from itholic/SPARK-37657.

Lead-authored-by: itholic <haejoon.lee@databricks.com>
Co-authored-by: Hyukjin Kwon <gurwls223@gmail.com>
Co-authored-by: Haejoon Lee <44108233+itholic@users.noreply.github.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>