[SPARK-43081][FOLLOW-UP][ML][CONNECT] Make torch dataloader support torch 1.x
### What changes were proposed in this pull request?

Make torch dataloader support torch 1.x.
Currently, when running with torch 1.x with num_workers > 0, an error is raised like:
```
ValueError: prefetch_factor option could only be specified in multiprocessing.let num_workers > 0 to enable multiprocessing.
```

### Why are the changes needed?

Compatibility fix.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manually run unit tests with torch 1.x

Closes #41751 from WeichenXu123/support-torch-1.x.

Authored-by: Weichen Xu <weichen.xu@databricks.com>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>