[SPARK-41256][CONNECT][FOLLOWUP] Fix compile error
### What changes were proposed in this pull request?

https://github.com/apache/spark/commit/8c71f06b3e3ea863cd12e541a9b7fad3d20e19eb made a breaking change in proto message, and cause https://github.com/apache/spark/commit/3de1f03a89a3fe35da3a27004443259296a77275 failed after merged

### Why are the changes needed?
to fix compile error:

```
[error] /__w/spark/spark/connector/connect/src/test/scala/org/apache/spark/sql/connect/planner/SparkConnectPlannerSuite.scala:441:67: value setI32 is not a member of org.apache.spark.connect.proto.Expression.Literal.Builder
[error]                   .setLiteral(proto.Expression.Literal.newBuilder.setI32(32))))
[error]                                                                   ^
[error] /__w/spark/spark/connector/connect/src/test/scala/org/apache/spark/sql/connect/planner/SparkConnectPlannerSuite.scala:446:67: value setI32 is not a member of org.apache.spark.connect.proto.Expression.Literal.Builder
[error]                   .setLiteral(proto.Expression.Literal.newBuilder.setI32(32)))))
[error]                                                                   ^
[error] /__w/spark/spark/connector/connect/src/test/scala/org/apache/spark/sql/connect/planner/SparkConnectPlannerSuite.scala:466:69: value setI32 is not a member of org.apache.spark.connect.proto.Expression.Literal.Builder
[error]                     .setLiteral(proto.Expression.Literal.newBuilder.setI32(32)))))
[error]                                                                     ^
[error] three errors found
```

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
local test

Closes #38837 from zhengruifeng/connect_hot_fix.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>