[SPARK-52238][TESTS][FOLLOW-UP] Fix test failure in classic-only envs
### What changes were proposed in this pull request?
fix import error in classic-only envs:

- pypy3.10
- python3.11-classic-only
- python3.13-nogil

### Why are the changes needed?

https://github.com/apache/spark/actions/runs/15430761771/job/43428094456

```
Starting test(python3.11): pyspark.pipelines.tests.test_block_connect_access (temp output: /__w/spark/spark/python/target/e57e05b9-80f9-4149-9a9c-898cf497bd80/python3.11__pyspark.pipelines.tests.test_block_connect_access__wv66e6_5.log)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/__w/spark/spark/python/pyspark/pipelines/tests/test_block_connect_access.py", line 21, in <module>
    from pyspark.pipelines.block_connect_access import block_spark_connect_execution_and_analysis
  File "/__w/spark/spark/python/pyspark/pipelines/block_connect_access.py", line 21, in <module>
    from pyspark.sql.connect.proto.base_pb2_grpc import SparkConnectServiceStub
  File "/__w/spark/spark/python/pyspark/sql/connect/proto/__init__.py", line 18, in <module>
    from pyspark.sql.connect.proto.base_pb2_grpc import *
  File "/__w/spark/spark/python/pyspark/sql/connect/proto/base_pb2_grpc.py", line 19, in <module>
    import grpc
ModuleNotFoundError: No module named 'grpc'
```

### Does this PR introduce _any_ user-facing change?
no, test-only

### How was this patch tested?
PR builder with
```
default: '{"PYSPARK_IMAGE_TO_TEST": "python-311-classic-only", "PYTHON_TO_TEST": "python3.11"}'
```

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #51094 from zhengruifeng/fix_pp_no_grpc.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>