[SPARK-43543][PYTHON] Fix nested MapType behavior in Pandas UDF
### What changes were proposed in this pull request?
Fix nested MapType behavior in Pandas UDF (and Arrow-optimized Python UDF).

Previously during Arrow-pandas conversion, only the outermost layer is converted to a dictionary; but now nested MapType will be converted to nested dictionaries.

That applies to Spark Connect as well.

### Why are the changes needed?
Correctness and consistency (with `createDataFrame` and `toPandas` when Arrow is enabled).

### Does this PR introduce _any_ user-facing change?
Yes.

Nested MapType type support is corrected in Pandas UDF

```py
>>> schema = StructType([
...      StructField("id", StringType(), True),
...      StructField("attributes", MapType(StringType(), MapType(StringType(), StringType())), True)
... ])
>>>
>>> data = [
...    ("1", {"personal": {"name": "John", "city": "New York"}}),
... ]
>>> df = spark.createDataFrame(data, schema)
>>> pandas_udf(StringType())
... def f(s: pd.Series) -> pd.Series:
...    return s.astype(str)
...
>>> df.select(f(df.attributes)).show(truncate=False)
```

The results of `df.select(f(df.attributes)).show(truncate=False)` is corrected

**FROM**
```py

+------------------------------------------------------+
|f(attributes)                                         |
+------------------------------------------------------+
|{'personal': [('name', 'John'), ('city', 'New York')]}|
+------------------------------------------------------+
```

**TO**
```py
>>> df.select(f(df.attributes)).show(truncate=False)
+--------------------------------------------------+
|f(attributes)                                     |
+--------------------------------------------------+
|{'personal': {'name': 'John', 'city': 'New York'}}|
+--------------------------------------------------+

```

**Another more obvious example:**
```py
>>> pandas_udf(StringType())
... def extract_name(s:pd.Series) -> pd.Series:
...     return s.apply(lambda x: x['personal']['name'])
...
>>> df.select(extract_name(df.attributes)).show(truncate=False)
```

`df.select(extract_name(df.attributes)).show(truncate=False)` is corrected

**FROM**
```py
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
...
TypeError: list indices must be integers or slices, not str
```

**TO**
```py
+------------------------+
|extract_name(attributes)|
+------------------------+
|John                    |
+------------------------+
```

### How was this patch tested?
Unit tests.

Closes #41147 from xinrong-meng/nestedType.

Authored-by: Xinrong Meng <xinrong@apache.org>
Signed-off-by: Xinrong Meng <xinrong@apache.org>