[SPARK-51567][ML][CONNECT] Fix `DistributedLDAModel.vocabSize`
### What changes were proposed in this pull request?
Fix `DistributedLDAModel.vocabSize`

### Why are the changes needed?
```
pyspark.errors.exceptions.connect.SparkException: [CONNECT_ML.ATTRIBUTE_NOT_ALLOWED] Generic Spark Connect ML error. vocabSize in org.apache.spark.ml.clustering.DistributedLDAModel is not allowed to be accessed. SQLSTATE: XX000

JVM stacktrace:
org.apache.spark.sql.connect.ml.MLAttributeNotAllowedException
	at org.apache.spark.sql.connect.ml.MLUtils$.validate(MLUtils.scala:686)
	at org.apache.spark.sql.connect.ml.MLUtils$.invokeMethodAllowed(MLUtils.scala:691)
	at org.apache.spark.sql.connect.ml.AttributeHelper.$anonfun$getAttribute$1(MLHandler.scala:56)
```

### Does this PR introduce _any_ user-facing change?
yes, new api supported

### How was this patch tested?
added test

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #50330 from zhengruifeng/ml_connect_lda_vocabSize.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>