[SPARK-39827][SQL] Use the error class `ARITHMETIC_OVERFLOW` on int overflow in `add_months()`
### What changes were proposed in this pull request?
In the PR, I propose to use `toIntExact()` from Spark's `MathUtils` instead of standard `Math.toIntExact` in the `AddMonths` expression. As a consequence of that, the `add_months()` function will raise `SparkArithmeticException` w/ the error class `ARITHMETIC_OVERFLOW` when integer overflow occurs.

### Why are the changes needed?
This should improve user experience with Spark SQL by showing unified errors w/ error classes to users.

### Does this PR introduce _any_ user-facing change?
No, it shouldn't because `SparkArithmeticException` is a sub-class of `ArithmeticException` but the error will look differently.

Before:
```sql
spark-sql> SELECT add_months('5500000-12-31', 10000000);
22/07/20 19:21:10 ERROR SparkSQLDriver: Failed in [SELECT add_months('5500000-12-31', 10000000)]
java.lang.ArithmeticException: integer overflow
	at java.lang.Math.toIntExact(Math.java:1011)
```

After:
```sql
spark-sql> SELECT add_months('5500000-12-31', 10000000);
org.apache.spark.SparkArithmeticException: [ARITHMETIC_OVERFLOW] integer overflow. If necessary set spark.sql.ansi.enabled to "false" (except for ANSI interval type) to bypass this error.
	at org.apache.spark.sql.errors.QueryExecutionErrors$.arithmeticOverflowError(QueryExecutionErrors.scala:484)
```

### How was this patch tested?
By running new test:
```
$ build/sbt "test:testOnly *QueryExecutionErrorsSuite"
```

Closes #37240 from MaxGekk/use-error-class-in-add_months.

Authored-by: Max Gekk <max.gekk@gmail.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>