[SPARK-36968][PYTHON] ps.Series.dot raise "matrices are not aligned" if index is not same
### What changes were proposed in this pull request?
Raise ValueError "matrices are not aligned" if index is not same for ps.Series.dot

### Why are the changes needed?
Follow pandas

### Does this PR introduce _any_ user-facing change?
Before this PR
```python
>>> psdf1 = ps.Series([1, 2, 3], index=[0, 1, 2])
>>> psdf2 = ps.Series([1, 2, 3], index=[0, 1, 3])
>>> psdf1.dot(psdf2)
5
```

After this PR
```python
>>> psdf1 = ps.Series([1, 2, 3], index=[0, 1, 2])
>>> psdf2 = ps.Series([1, 2, 3], index=[0, 1, 3])
>>> psdf1.dot(psdf2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u02/spark/python/pyspark/pandas/series.py", line 5003, in dot
    raise ValueError("matrices are not aligned")
ValueError: matrices are not aligned
```
### How was this patch tested?
unit test

Closes #34235 from dchvn/SPARK-36968.

Authored-by: dch nguyen <dgd_contributor@viettel.com.vn>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>