[SPARK-36989][TESTS][PYTHON][FOLLOW-UP] Move pyproject.toml from python to dev directory
### What changes were proposed in this pull request?

This PR is a minor folllowup that proposes to move `python/pyproject.toml` to `dev/pyproject.toml`.

### Why are the changes needed?

`pyproject.toml` can potentially affect how PySpark package interacts with pip. For example, the fork of PySpark in Databricks attempts to build a wheel as a test. Previously, it passed permissively but now it fails as below:

```
ERROR: Could not build wheels for pyspark, which is required to install pyproject.toml-based projects
```

Since `python/pyproject.toml` is only for tests, it should be best to minimise such potential impact.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Tested in the CI of the fork.

Closes #34481 from HyukjinKwon/SPARK-36989-followup.

Authored-by: Hyukjin Kwon <gurwls223@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>