[SPARK-39309][PYTHON][INFRA] Change xmlrunner to unittest-xml-reporting
### What changes were proposed in this pull request?
The xmlrunner had been moved to https://github.com/xmlrunner/unittest-xml-reporting

### Why are the changes needed?
As metioned in SPARK-39309, I encountered a issue like: `AttributeError: '_SubTest' object has no attribute 'elapsed_time'`, according to https://github.com/xmlrunner/unittest-xml-reporting/issues/218#issuecomment-665088941 , I found that xmlrunner has been switch to `unittest-xml-reporting`.

We'd better to upgrade xmlrunner to avoid these kind of legacy issues.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
- Test on my local env
- CI passed

Closes #37448 from Yikun/SPARK-39309.

Authored-by: Yikun Jiang <yikunkero@gmail.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>