[SPARK-41595][SQL] Support generator function explode/explode_outer in the FROM clause
### What changes were proposed in this pull request?
This PR supports using table-valued generator functions in the FROM clause of a query. A generator function can be registered in the table function registry and resolved as a table function during analysis.

Note this PR only adds support for two built-in generator functions: `explode` and `explode_outer` with literal input values. We will support more generator functions and LATERAL references in separate PRs.

### Why are the changes needed?
To make table-valued generator functions more user-friendly and consistent with Spark's built-in table function Range.

### Does this PR introduce _any_ user-facing change?
Yes. Before this PR, the built-in generator function explode/explode_outer cannot be used in the FROM clause:
```
select * from explode(array(1, 2))

AnalysisException: could not resolve `explode` to a table-valued function;
```
After this PR, we can support this usage:
```
select * from explode(array(1, 2))

+---+
|col|
+---+
|  1|
|  2|
+---+
```

### How was this patch tested?

New SQL query tests.

Closes #39133 from allisonwang-db/spark-41595-explode-in-from.

Authored-by: allisonwang-db <allison.wang@databricks.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>