[SPARK-42017][PYTHON][CONNECT] df['col_name']` should validate the column name
### What changes were proposed in this pull request?
make `df['col_name']` validate the column name

### Why are the changes needed?
for parity

### Does this PR introduce _any_ user-facing change?
yes

before

```
In [1]: df = spark.range(0, 10)

In [2]: df["bad_key"]
Out[2]: Column<'bad_key'>

```

after

```
In [1]: df = spark.range(0, 10)

In [2]: df["bad_key"]
23/08/23 17:23:35 ERROR ErrorUtils: Spark Connect RPC error during: analyze. UserId: ruifeng.zheng. SessionId: 59de3f10-14b6-4239-be85-4156da43d495.
org.apache.spark.sql.AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `bad_key` cannot be resolved. Did you mean one of the following? [`id`].;
'Project ['bad_key]
+- Range (0, 10, step=1, splits=Some(12))

...

AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `bad_key` cannot be resolved. Did you mean one of the following? [`id`].;
'Project ['bad_key]
+- Range (0, 10, step=1, splits=Some(12))
```

### How was this patch tested?
enabled UT

### Was this patch authored or co-authored using generative AI tooling?
NO

Closes #42608 from zhengruifeng/tests_enable_test_access_column.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>