[SPARK-46413][PYTHON] Validate returnType of Arrow Python UDF
### What changes were proposed in this pull request?
Validate returnType of Arrow Python UDF

### Why are the changes needed?
Better error handling and consistency with other types of UDFs.

### Does this PR introduce _any_ user-facing change?
Yes, now we raise an error when the given returnType is not supported.

```py
>>> udf(lambda x: x, returnType=VarcharType(10), useArrow=True)
Traceback (most recent call last):
...
pyspark.errors.exceptions.base.PySparkTypeError: [UNSUPPORTED_DATA_TYPE_FOR_ARROW_CONVERSION] VarcharType(10) is not supported in conversion to Arrow.
```

### How was this patch tested?
Unit tests.

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #44362 from xinrong-meng/test_more_udf.

Authored-by: Xinrong Meng <xinrong@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>