[SPARK-47420][SQL] Fix test output
Make "AssertionFailedError: expected: <true> but was: <false>" to be rendered correctly

### What changes were proposed in this pull request?
The assertion was being rendered the other way around

### Why are the changes needed?
To avoid confusion during test checks

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
`testOnly org.apache.spark.unsafe.types.CollationSupportSuite`

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #46058 from vladimirg-db/vladimirg-db/fix-test-output.

Authored-by: Vladimir Golubev <vladimir.golubev@databricks.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>