[SPARK-50511][PYTHON] Avoid wrapping Python data source error messages
### What changes were proposed in this pull request?

This PR removes the extra try catch during Python data source creation and planning. This is to avoid the redundancy of having `During handling of the above exception, another exception occurred`:
```
AnalysisException: [PYTHON_DATA_SOURCE_ERROR] Failed to create Python data source instance: Traceback (most recent call last):
  File "/Users/allison.wang/oss/spark/python/pyspark/sql/worker/create_data_source.py", line 145, in main
    raise PySparkRuntimeError(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/allison.wang/oss/spark/python/pyspark/sql/datasource.py", line 118, in schema
    raise PySparkNotImplementedError(
pyspark.errors.exceptions.base.PySparkNotImplementedError: [NOT_IMPLEMENTED] schema is not implemented.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/allison.wang/oss/spark/python/pyspark/sql/worker/create_data_source.py", line 151, in main
pyspark.errors.exceptions.base.PySparkRuntimeError: [NOT_IMPLEMENTED] DataSource.schema is not implemented.
 SQLSTATE: 38000
```

### Why are the changes needed?

To improve error messages

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests

### Was this patch authored or co-authored using generative AI tooling?

No

Closes #49092 from allisonwang-db/spark-50511-pyds-err-msg.

Authored-by: Allison Wang <allison.wang@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>