Revert "[SPARK-52610][BUILD] Upgrade rocksdbjni to 10.2.1"
### What changes were proposed in this pull request?
This pr reverts commit 37e7f1c57d87c4d0ec945521ebc024d59691fd4e to downgrade rocksdbjni from 10.2.1 to 9.8.4.

### Why are the changes needed?
Rocksdbjni 10.2.1 crashed during testing:

- https://github.com/apache/spark/actions/runs/16638741674/job/47084788641

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
03:55:47.848 WARN org.apache.spark.scheduler.DAGScheduler: Failed to cancel job group 2d75e504-d47d-4eb3-ac5b-1ce066ae486b. Cannot find active jobs for it.

#  SIGSEGV (0xb) at pc=0x00007f8d46c7eed9, pid=25508, tid=653254
#
# JRE version: OpenJDK Runtime Environment Zulu17.60+17-CRaC-CA (17.0.16+8) (build 17.0.16+8-LTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu17.60+17-CRaC-CA (17.0.16+8-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C03:55:47.850 ERROR org.apache.spark.util.Utils: Aborting task
org.apache.spark.SparkException: [CANNOT_WRITE_STATE_STORE.CANNOT_COMMIT] Error writing state store files for provider RocksDBStateStore[stateStoreId=StateStoreId[ operatorId=0, partitionId=2, storeName=default ], version=18]. Cannot perform commit during state checkpoint. SQLSTATE: 58030
	at org.apache.spark.sql.errors.QueryExecutionErrors$.failedToCommitStateFileError(QueryExecutionErrors.scala:2249)
	at org.apache.spark.sql.execution.streaming.state.RocksDBStateStoreProvider$RocksDBStateStore.commit(RocksDBStateStoreProvider.scala:392)
	at org.apache.spark.sql.execution.streaming.TransformWithStateExec.$anonfun$processDataWithPartition$5(TransformWithStateExec.scala:341)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.apache.spark.util.Utils$.timeTakenMs(Utils.scala:482)
	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs(statefulOperators.scala:406)
	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs$(statefulOperators.scala:406)
  [librocksdbjni3950065922734541121.so+0x47eed9]03:55:47.851 ERROR org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask: Aborting commit for partition 2 (task 465, attempt 0, stage 161.0)

03:55:47.851 ERROR org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask: Aborted commit for partition 2 (task 465, attempt 0, stage 161.0)

  rocksdb::DBImpl::FailIfCfHasTs(rocksdb::ColumnFamilyHandle const*) const+0x29
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t 9223372036854775808 %h %d" (or dumping to /home/runner/work/spark/spark/sql/core/core.25508)
#
# An error report file with more information is saved as:
# /home/runner/work/spark/spark/sql/core/hs_err_pid25508.log
03:55:47.852 WARN org.apache.spark.scheduler.TaskSetManager: Lost task 2.0 in stage 161.0 (TID 465) (localhost executor driver): TaskKilled (Stage cancelled: [SPARK_JOB_CANCELLED] Job 89 cancelled Query [id = a4a0ad54-035d-4049-961c-a36ee70e3d7c, runId = 2d75e504-d47d-4eb3-ac5b-1ce066ae486b] was stopped SQLSTATE: XXKDA)

#
# If you would like to submit a bug report, please visit:
#   http://www.azul.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass Github Actions

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #51750 from LuciferYang/revert-SPARK-52610.

Authored-by: yangjie01 <yangjie01@baidu.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>