[SPARK-38979][SQL] Improve error log readability in OrcUtils.requestedColumnIds
### What changes were proposed in this pull request?
Add detailed log in `OrcUtils#requestedColumnIds`.

### Why are the changes needed?
In `OrcUtils#requestedColumnIds` sometimes it fails because `orcFieldNames.length > dataSchema.length`, the log is not very clear.

```
java.lang.AssertionError: assertion failed: The given data schema struct<field1:int> has less fields than the actual ORC physical schema, no idea which columns were dropped, fail to read.
```

after the change
```
java.lang.AssertionError: assertion failed: The given data schema struct<field1:int> (length:1) has fewer 1 fields than the actual ORC physical schema struct<field1:int,field2:int> (length:2), no idea which columns were dropped, fail to read.
```

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
exist UT / local test

Closes #36296 from cxzl25/SPARK-38979.

Authored-by: sychen <sychen@ctrip.com>
Signed-off-by: Sean Owen <srowen@gmail.com>