[SPARK-34521][PYTHON][SQL] Fix spark.createDataFrame when using pandas with StringDtype
### What changes were proposed in this pull request?

This change fixes `SPARK-34521`. It allows creating a spark DataFrame from a pandas DataFrame that is using a `StringDtype` column and arrow pyspark enabled.

### Why are the changes needed?

Pandas stores string columns in two different ways: using a numpy `ndarray` or using a custom `StringArray`. The `StringArray` version is used when specifing the `dtype=string`. When that happens, spark cannot serialize the column to arrow. Converting the `Series` before fixes this problem.

However, due to the different ways to handle string columns, doing `spark.createDataFrame(pandas_dataframe).toPandas()` might not equal to `pandas_dataframe`. The column dtype could be different.

More info: https://pandas.pydata.org/docs/user_guide/text.html

### Does this PR introduce _any_ user-facing change?

Trying to create a spark `DataFrame` from a pandas `DataFrame` using a string dtype and `"spark.sql.execution.arrow.pyspark.enabled"` now doesn't throw an exception and returns the expected dataframe.

Before:

`spark.createDataFrame(pd.DataFrame({"A": ['a', 'b', 'c']}, dtype="string"))`
```
Error
Traceback (most recent call last):
  File "/home/nico/projects/playground/spark/python/pyspark/sql/tests/test_arrow.py", line 415, in test_createDataFrame_with_string_dtype
    print(self.spark.createDataFrame(pd.DataFrame({"A": ['a', 'b', 'c']}, dtype="string")))
  File "/home/nico/projects/playground/spark/python/pyspark/sql/session.py", line 823, in createDataFrame
    return super(SparkSession, self).createDataFrame(  # type: ignore[call-overload]
  File "/home/nico/projects/playground/spark/python/pyspark/sql/pandas/conversion.py", line 358, in createDataFrame
    return self._create_from_pandas_with_arrow(data, schema, timezone)
  File "/home/nico/projects/playground/spark/python/pyspark/sql/pandas/conversion.py", line 550, in _create_from_pandas_with_arrow
    self._sc  # type: ignore[attr-defined]
  File "/home/nico/projects/playground/spark/python/pyspark/context.py", line 611, in _serialize_to_jvm
    serializer.dump_stream(data, tempFile)
  File "/home/nico/projects/playground/spark/python/pyspark/sql/pandas/serializers.py", line 221, in dump_stream
    super(ArrowStreamPandasSerializer, self).dump_stream(batches, stream)
  File "/home/nico/projects/playground/spark/python/pyspark/sql/pandas/serializers.py", line 81, in dump_stream
    for batch in iterator:
  File "/home/nico/projects/playground/spark/python/pyspark/sql/pandas/serializers.py", line 220, in <genexpr>
    batches = (self._create_batch(series) for series in iterator)
  File "/home/nico/projects/playground/spark/python/pyspark/sql/pandas/serializers.py", line 211, in _create_batch
    arrs.append(create_array(s, t))
  File "/home/nico/projects/playground/spark/python/pyspark/sql/pandas/serializers.py", line 185, in create_array
    raise e
  File "/home/nico/projects/playground/spark/python/pyspark/sql/pandas/serializers.py", line 175, in create_array
    array = pa.Array.from_pandas(s, mask=mask, type=t, safe=self._safecheck)
  File "pyarrow/array.pxi", line 904, in pyarrow.lib.Array.from_pandas
  File "pyarrow/array.pxi", line 252, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 107, in pyarrow.lib._handle_arrow_array_protocol
ValueError: Cannot specify a mask or a size when passing an object that is converted with the __arrow_array__ protocol.

```

After:

`spark.createDataFrame(pd.DataFrame({"A": ['a', 'b', 'c']}, dtype="string"))`
> `DataFrame[A: string]`

### How was this patch tested?

Using the `test_createDataFrame_with_string_dtype` test.

Closes #34509 from nicolasazrak/SPARK-34521.

Authored-by: Nicolas Azrak <azrak.nicolas@gmail.com>
Signed-off-by: Bryan Cutler <cutlerb@gmail.com>