[SPARK-52238][TESTS][FOLLOW-UP] Fix test failure in daily builds
### What changes were proposed in this pull request?
python 3.12/3.13 were broken:

```
======================================================================
ERROR [0.019s]: test_collect_blocked (__main__.BlockSparkConnectAccessTests.test_collect_blocked)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/spark/spark/python/pyspark/pipelines/tests/test_block_connect_access.py", line 51, in test_collect_blocked
    self.assertEquals(
    ^^^^^^^^^^^^^^^^^
AttributeError: 'BlockSparkConnectAccessTests' object has no attribute 'assertEquals'. Did you mean: 'assertEqual'?

======================================================================
ERROR [0.016s]: test_schema_access_blocked (__main__.BlockSparkConnectAccessTests.test_schema_access_blocked)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/spark/spark/python/pyspark/pipelines/tests/test_block_connect_access.py", line 41, in test_schema_access_blocked
    self.assertEquals(
    ^^^^^^^^^^^^^^^^^
AttributeError: 'BlockSparkConnectAccessTests' object has no attribute 'assertEquals'. Did you mean: 'assertEqual'?

----------------------------------------------------------------------
Ran 5 tests in 7.175s
```

### Why are the changes needed?
to make CI happy

### Does this PR introduce _any_ user-facing change?
no, test-only

### How was this patch tested?
PR build with
```
default: '{"PYSPARK_IMAGE_TO_TEST": "python-312", "PYTHON_TO_TEST": "python3.12"}'
```

https://github.com/zhengruifeng/spark/actions/runs/15407621295/job/43353257681

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #51067 from zhengruifeng/fix_assert_equals.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>