[SPARK-44044][SS] Improve Error message for Window functions with streaming
### What changes were proposed in this pull request?
Replace existing error message when non-time window function is used with streaming to include aggregation function and column. The error message looks like following now:

org.apache.spark.sql.AnalysisException: Window function is not supported in 'row_number()' as column 'rn_col' on streaming DataFrames/Datasets. Structured Streaming only supports time-window aggregation using the `window` unction. (window specification: '(PARTITION BY col1 ORDER BY col2 ASC NULLS FIRST ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)')

Note that the message is a little bit unnatural as the existing unit test requires the exception follows the pattern that it includes "not supported", "streaming" "DataFrames" and "Dataset".

### Why are the changes needed?
The exiting error message is vague and a full logical plan is included. A user reports that they aren't able to identify what the problem is.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Added a unit test

Closes #41578 from siying/window_error.

Lead-authored-by: Siying Dong <siying.dong@databricks.com>
Co-authored-by: Siying Dong <dong.sy@gmail.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>