[MINOR][PYTHON][TESTS] De-flake unit tests of `collect_set` and `collect_list` in `test_connect_function`
### What changes were proposed in this pull request?
De-flake unit tests of `collect_set` and `collect_list`, by sorting the output arrays

### Why are the changes needed?
the tests occasionally fail with
```
AssertionError: DataFrame.iloc[:, 0] (column name="r1") are different
DataFrame.iloc[:, 0] (column name="r1") values are different (100.0 %)
[index]: [0]
[left]:  [[nan, 2.1, 0.5]]
[right]: [[2.1, nan, 0.5]]
At positional index 0, first diff: [nan 2.1 0.5] != [2.1 nan 0.5]
```

### Does this PR introduce _any_ user-facing change?
no, test-only

### How was this patch tested?
CI

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #51511 from zhengruifeng/fix_agg_test_2.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>