[SPARK-52721][PYTHON] Fix message parameter for CANNOT_PARSE_DATATYPE
### What changes were proposed in this pull request?

Fix message parameter for CANNOT_PARSE_DATATYPE

### Why are the changes needed?
bugfix

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

- Before
AssertionError: Undefined error message parameter for error class: CANNOT_PARSE_DATATYPE. Parameters: {'error':

- After
pyspark.errors.exceptions.base.PySparkValueError: [CANNOT_PARSE_DATATYPE] Unable to parse datatype.

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #51414 from yaooqinn/SPARK-52721.

Authored-by: Kent Yao <yao@apache.org>
Signed-off-by: Kent Yao <yao@apache.org>
(cherry picked from commit ecd77a343f5d6bd2a29fb96c92085cd2b8032e6a)
Signed-off-by: Kent Yao <yao@apache.org>