[SPARK-49578][SQL] Remove the ANSI config suggestion in CAST_INVALID_INPUT and CAST_OVERFLOW
### What changes were proposed in this pull request?
Removal of suggestion to turn off ansi when experiencing CAST_INVALID_INPUT or CAST_OVERFLOW.

### Why are the changes needed?
These errors already contain sufficient suggestions, amongst which one is to use `try_cast` in place of `cast`. This removal of ANSI turn off suggestion is part of a movement to keep suggestions of not using ANSI in code to minimum.

### Does this PR introduce _any_ user-facing change?
Yes. This PR is changing user-facing error message.
Previous state:
```
SELECT CAST('a' AS INT)
org.apache.spark.SparkNumberFormatException: [CAST_INVALID_INPUT] The value 'a' of the type "STRING" cannot be cast to "INT" because it is malformed. Correct the value as per the syntax, or change its target type. Use `try_cast` to tolerate malformed input and return NULL instead. If necessary set "spark.sql.ansi.enabled" to "false" to bypass this error.
SELECT CAST(2147483648L AS INT);
org.apache.spark.SparkArithmeticException: [CAST_OVERFLOW] The value 2147483648L of the type "BIGINT" cannot be cast to "INT" due to an overflow. Use `try_cast` to tolerate overflow and return NULL instead. If necessary set "spark.sql.ansi.enabled" to "false" to bypass this error.
```

Current state:
```
SELECT CAST('a' AS INT)
org.apache.spark.SparkNumberFormatException: [CAST_INVALID_INPUT] The value 'a' of the type "STRING" cannot be cast to "INT" because it is malformed. Correct the value as per the syntax, or change its target type. Use `try_cast` to tolerate malformed input and return NULL instead.
SELECT CAST(2147483648L AS INT);
org.apache.spark.SparkArithmeticException: [CAST_OVERFLOW] The value 2147483648L of the type "BIGINT" cannot be cast to "INT" due to an overflow. Use `try_cast` to tolerate overflow and return NULL instead.
```

### How was this patch tested?
Existing tests check for existence of ansiConfig message parameter.

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #48054 from mihailom-db/ANSI-errors.

Authored-by: Mihailo Milosevic <mihailo.milosevic@databricks.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>