[SPARK-46925][PYTHON][CONNECT] Add a warning that instructs to install memory_profiler for memory profiling
### What changes were proposed in this pull request?
Add a warning that instructs to install memory_profiler for memory profiling.

### Why are the changes needed?
To inform users why calling a method like spark.showMemoryProfiles() would return empty results if the memory_profiler module isn't installed.
Better usability.

### Does this PR introduce _any_ user-facing change?
No behavior change, only a warning is added.

```python
>>> import memory_profiler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'memory_profiler']

...

>>> spark.showMemoryProfiles()
UserWarning: Memory profiling is disabled. To enable it, install 'memory-profiler' from PyPI (https://pypi.org/project/memory-profiler/).
```

### How was this patch tested?
Manual tests.

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #44958 from xinrong-meng/memory_warning.

Lead-authored-by: Xinrong Meng <xinrong@apache.org>
Co-authored-by: Hyukjin Kwon <gurwls223@gmail.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>